/* JS */ gapi.loaded_3(function(_){var window=this;
_.Lh={};_.Mh=function(a){return _.Lh[a||"token"]||null};

_.Sy=function(a){if(0!==a.indexOf("GCSC"))return null;var b={uA:!1};a=a.substr(4);if(!a)return b;var c=a.charAt(0);a=a.substr(1);var d=a.lastIndexOf("_");if(-1==d)return b;var e=_.Qy(a.substr(d+1));if(null==e)return b;a=a.substring(0,d);if("_"!==a.charAt(0))return b;d="E"===c&&e.xe;return!d&&("U"!==c||e.xe)||d&&!_.Ry?b:{uA:!0,xe:d,hQ:a.substr(1),domain:e.domain,kh:e.kh}};
_.Ty=function(a,b){this.sd=a;a=b||{};this.XV=Number(a.maxAge)||0;this.vc=a.domain;this.nk=a.path;this.sY=!!a.secure};_.Ty.prototype.read=function(){for(var a=this.sd+"=",b=document.cookie.split(/;\s*/),c=0;c<b.length;++c){var d=b[c];if(0==d.indexOf(a))return d.substr(a.length)}};
_.Ty.prototype.write=function(a,b){if(!Uy.test(this.sd))throw"Invalid cookie name";if(!Vy.test(a))throw"Invalid cookie value";a=this.sd+"="+a;this.vc&&(a+=";domain="+this.vc);this.nk&&(a+=";path="+this.nk);b="number"===typeof b?b:this.XV;if(0<=b){var c=new Date;c.setSeconds(c.getSeconds()+b);a+=";expires="+c.toUTCString()}this.sY&&(a+=";secure");document.cookie=a;return!0};_.Ty.prototype.clear=function(){this.write("",0)};var Vy=/^[-+/_=.:|%&a-zA-Z0-9@]*$/,Uy=/^[A-Z_][A-Z0-9_]{0,63}$/;
_.Ty.iterate=function(a){for(var b=document.cookie.split(/;\s*/),c=0;c<b.length;++c){var d=b[c].split("="),e=d.shift();a(e,d.join("="))}};
_.Wy=function(a){this.Gh=a};_.Wy.prototype.read=function(){if(Xy.hasOwnProperty(this.Gh))return Xy[this.Gh]};_.Wy.prototype.write=function(a){Xy[this.Gh]=a;return!0};_.Wy.prototype.clear=function(){delete Xy[this.Gh]};var Xy={};_.Wy.iterate=function(a){for(var b in Xy)Xy.hasOwnProperty(b)&&a(b,Xy[b])};
var Yy=function(){this.ee=null;this.key=function(){return null};this.getItem=function(){return this.ee};this.setItem=function(a,b){this.ee=b;this.length=1};this.removeItem=function(){this.clear()};this.clear=function(){this.ee=null;this.length=0};this.length=0},Zy=function(a){try{var b=a||window.sessionStorage;if(!b)return!1;b.setItem("gapi.sessionStorageTest","gapi.sessionStorageTest"+b.length);b.removeItem("gapi.sessionStorageTest");return!0}catch(c){return!1}},mz=function(a,b){this.sd=a;this.Jf=
Zy(b)?b||window.sessionStorage:new Yy};mz.prototype.read=function(){return this.Jf.getItem(this.sd)};mz.prototype.write=function(a){try{this.Jf.setItem(this.sd,a)}catch(b){return!1}return!0};mz.prototype.clear=function(){this.Jf.removeItem(this.sd)};mz.iterate=function(a){if(Zy())for(var b=0,c=window.sessionStorage.length;b<c;++b){var d=window.sessionStorage.key(b);a(d,window.sessionStorage[d])}};
for(var xz=0;64>xz;++xz);
_.Ry="https:"===window.location.protocol;_.yz=_.Ry||"http:"===window.location.protocol?_.Ty:_.Wy;_.Qy=function(a){var b=a.substr(1),c="",d=window.location.hostname;if(""!==b){c=parseInt(b,10);if(isNaN(c))return null;b=d.split(".");if(b.length<c-1)return null;b.length==c-1&&(d="."+d)}else d="";return{xe:"S"==a.charAt(0),domain:d,kh:c}};
var zz,Az,Dz,Ez;zz=_.me();Az=_.me();_.Bz=_.me();_.Cz=_.me();Dz="state code cookie_policy g_user_cookie_policy authuser prompt g-oauth-window status".split(" ");Ez=function(a){this.VJ=a;this.QA=null};
Ez.prototype.write=function(a){var b=_.me(),c=_.me(),d=window.decodeURIComponent?decodeURIComponent:unescape,e;for(e in a)if(_.ne(a,e)){var f=a[e];f=f.replace(/\+/g," ");c[e]=d(f);b[e]=a[e]}d=0;for(e=Dz.length;d<e;++d)delete c[Dz[d]];a=String(a.authuser||0);d=_.me();d[a]=c;c=_.yf(d);this.VJ.write(c);this.QA=b};Ez.prototype.read=function(){return this.QA};Ez.prototype.clear=function(){this.VJ.clear();this.QA=_.me()};_.Fz=function(a){return a?{domain:a.domain,path:"/",secure:a.xe}:null};
mz.iterate(function(a){var b=_.Sy(a);b&&b.uA&&(zz[a]=new Ez(new mz(a)))});_.yz.iterate(function(a){zz[a]&&(Az[a]=new _.yz(a,_.Fz(_.Sy(a))))});

_.og=window.gapi&&window.gapi.util||{};

_.og=_.og={};_.og.getOrigin=function(a){return _.qg(a)};

/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
_.dh=function(a){for(var b=[],c=0,d=0;d<a.length;d++){var e=a.charCodeAt(d);255<e&&(b[c++]=e&255,e>>=8);b[c++]=e}return b};
var eh;eh={};_.fh=null;_.gh=_.uc||_.vc&&!_.ch||_.qc||!_.ch&&!_.rc&&"function"==typeof _.C.atob;_.ih=function(a,b){void 0===b&&(b=0);_.hh();b=eh[b];for(var c=[],d=0;d<a.length;d+=3){var e=a[d],f=d+1<a.length,g=f?a[d+1]:0,k=d+2<a.length,l=k?a[d+2]:0,m=e>>2;e=(e&3)<<4|g>>4;g=(g&15)<<2|l>>6;l&=63;k||(l=64,f||(g=64));c.push(b[m],b[e],b[g]||"",b[l]||"")}return c.join("")};
_.hh=function(){if(!_.fh){_.fh={};for(var a="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),b=["+/=","+/","-_=","-_.","-_"],c=0;5>c;c++){var d=a.concat(b[c].split(""));eh[c]=d;for(var e=0;e<d.length;e++){var f=d[e];void 0===_.fh[f]&&(_.fh[f]=e)}}}};

/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var Ch;_.Bh=function(a){this.nb=a||{cookie:""}};_.h=_.Bh.prototype;_.h.isEnabled=function(){return navigator.cookieEnabled};
_.h.set=function(a,b,c){var d=!1;if("object"===typeof c){var e=c.V9;d=c.secure||!1;var f=c.domain||void 0;var g=c.path||void 0;var k=c.$I}if(/[;=\s]/.test(a))throw Error("y`"+a);if(/[;\r\n]/.test(b))throw Error("z`"+b);void 0===k&&(k=-1);this.nb.cookie=a+"="+b+(f?";domain="+f:"")+(g?";path="+g:"")+(0>k?"":0==k?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date(Date.now()+1E3*k)).toUTCString())+(d?";secure":"")+(null!=e?";samesite="+e:"")};
_.h.get=function(a,b){for(var c=a+"=",d=(this.nb.cookie||"").split(";"),e=0,f;e<d.length;e++){f=(0,_.qb)(d[e]);if(0==f.lastIndexOf(c,0))return f.substr(c.length);if(f==a)return""}return b};_.h.remove=function(a,b,c){var d=this.Od(a);this.set(a,"",{$I:0,path:b,domain:c});return d};_.h.re=function(){return Ch(this).keys};_.h.Sc=function(){return Ch(this).values};_.h.isEmpty=function(){return!this.nb.cookie};_.h.Fb=function(){return this.nb.cookie?(this.nb.cookie||"").split(";").length:0};
_.h.Od=function(a){return void 0!==this.get(a)};_.h.Dj=function(a){for(var b=Ch(this).values,c=0;c<b.length;c++)if(b[c]==a)return!0;return!1};_.h.clear=function(){for(var a=Ch(this).keys,b=a.length-1;0<=b;b--)this.remove(a[b])};Ch=function(a){a=(a.nb.cookie||"").split(";");for(var b=[],c=[],d,e,f=0;f<a.length;f++)e=(0,_.qb)(a[f]),d=e.indexOf("="),-1==d?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+1)));return{keys:b,values:c}};
_.Dh=new _.Bh("undefined"==typeof document?null:document);

var Uu,Vu,Wu,Xu,Zu,$u,av,bv,dv;oauth2={};_.Tu=!1;Uu=function(a){try{_.Tu&&window.console&&window.console.log&&window.console.log(a)}catch(b){}};Vu=function(a,b){if(!a)return-1;if(a.indexOf)return a.indexOf(b,void 0);for(var c=0,d=a.length;c<d;c++)if(a[c]===b)return c;return-1};Wu=function(a,b){function c(){}if(!a)throw"Child class cannot be empty.";if(!b)throw"Parent class cannot be empty.";c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a};
Xu=function(a){return"[object Function]"===Object.prototype.toString.call(a)};_.Yu=function(a){var b={};if(a)for(var c in a)a.hasOwnProperty(c)&&(b[c]=a[c]);return b};Zu=function(a){var b=location.hash;a=new RegExp("[&#]"+a+"=([^&]*)");b=decodeURIComponent(b);b=a.exec(b);return null==b?"":b[1].replace(/\+/g," ")};$u=function(a,b,c){if(a.addEventListener)a.addEventListener(b,c,!1);else if(a.attachEvent)a.attachEvent("on"+b,c);else throw"Add event handler for "+b+" failed.";};av={token:1,id_token:1};
bv=function(){var a=navigator.userAgent.toLowerCase();return-1!=a.indexOf("msie")&&8==parseInt(a.split("msie")[1],10)};_.cv=window.JSON;dv=function(a){this.wD=a||[];this.Xb={}};dv.prototype.addEventListener=function(a,b){if(!(0<=Vu(this.wD,a)))throw"Unrecognized event type: "+a;if(!Xu(b))throw"The listener for event '"+a+"' is not a function.";this.Xb[a]||(this.Xb[a]=[]);0>Vu(this.Xb[a],b)&&this.Xb[a].push(b)};
dv.prototype.removeEventListener=function(a,b){if(!(0<=Vu(this.wD,a)))throw"Unrecognized event type: "+a;Xu(b)&&this.Xb[a]&&this.Xb[a].length&&(b=Vu(this.Xb[a],b),0<=b&&this.Xb[a].splice(b,1))};dv.prototype.dispatchEvent=function(a){var b=a.type;if(!(b&&0<=Vu(this.wD,b)))throw"Failed to dispatch unrecognized event type: "+b;if(this.Xb[b]&&this.Xb[b].length)for(var c=0,d=this.Xb[b].length;c<d;c++)this.Xb[b][c](a)};
var ev,fv,gv,kv,lv,Cv,Dv,Fv,Gv,Iv,Rv;ev={};fv={};gv={google:{authServerUrl:"https://accounts.google.com/o/oauth2/auth",idpIFrameUrl:"https://accounts.google.com/o/oauth2/iframe"}};_.hv=function(a,b){if(a=gv[a])return a[b]};_.iv=function(a,b){if(!a)throw Error("M");if(!b.authServerUrl)throw Error("N");if(!b.idpIFrameUrl)throw Error("O");gv[a]={authServerUrl:b.authServerUrl,idpIFrameUrl:b.idpIFrameUrl}};_.jv=void 0;
kv=function(a){a.style.position="absolute";a.style.width="1px";a.style.height="1px";a.style.left="-9999px";a.style.top="-9999px";a.style.right="-9999px";a.style.bottom="-9999px";a.style.display="none";a.setAttribute("aria-hidden","true")};lv=function(){this.Q_=window;this.bt=this.Pk=this.Pq=this.Sg=null};
lv.prototype.open=function(a,b,c,d){mv(this);this.Pq?(this.Pk&&(this.Pk(),this.Pk=null),nv(this)):this.Pq="authPopup"+Math.floor(1E6*Math.random()+1);a:{this.Sg=this.Q_.open(a,this.Pq,b);try{this.Sg.focus();if(this.Sg.closed||"undefined"==typeof this.Sg.closed)throw Error("Q");_.jv=this.Sg}catch(e){d&&setTimeout(d,0);this.Sg=null;break a}c&&(this.Pk=c,ov(this))}};
var mv=function(a){try{if(null==a.Sg||a.Sg.closed)a.Sg=null,a.Pq=null,nv(a),a.Pk&&(a.Pk(),a.Pk=null)}catch(b){a.Sg=null,a.Pq=null,nv(a)}},ov=function(a){a.bt=window.setInterval(function(){mv(a)},300)},nv=function(a){a.bt&&(window.clearInterval(a.bt),a.bt=null)};fv=fv||{};var pv=function(a,b){this.Qb=a;this.pA=b;this.Wc=null;this.yl=!1};pv.prototype.start=function(){if(!this.yl&&!this.Wc){var a=this;this.Wc=window.setTimeout(function(){a.clear();a.yl||(a.Qb(),a.yl=!0)},fv.iH(this.pA))}};
pv.prototype.clear=function(){this.Wc&&(window.clearTimeout(this.Wc),this.Wc=null)};var qv=function(a,b){var c=fv.Do;this.FU=fv.xo;this.zM=c;this.Qb=a;this.pA=b;this.Wc=null;this.yl=!1;var d=this;this.AM=function(){document[d.FU]||(d.clear(),d.start())}};qv.prototype.start=function(){if(!this.yl&&!this.Wc){$u(document,this.zM,this.AM);var a=this;this.Wc=window.setTimeout(function(){a.clear();a.yl||(a.Qb(),a.yl=!0)},fv.iH(this.pA))}};
qv.prototype.clear=function(){var a=this.zM,b=this.AM,c=document;if(c.removeEventListener)c.removeEventListener(a,b,!1);else if(c.detachEvent)c.detachEvent("on"+a,b);else throw"Remove event handler for "+a+" failed.";this.Wc&&(window.clearTimeout(this.Wc),this.Wc=null)};fv.xo=null;fv.Do=null;
fv.bV=function(){var a=document;"undefined"!==typeof a.hidden?(fv.xo="hidden",fv.Do="visibilitychange"):"undefined"!==typeof a.msHidden?(fv.xo="msHidden",fv.Do="msvisibilitychange"):"undefined"!==typeof a.webkitHidden&&(fv.xo="webkitHidden",fv.Do="webkitvisibilitychange")};fv.bV();fv.uQ=function(a,b){return fv.xo&&fv.Do?new qv(a,b):new pv(a,b)};fv.iH=function(a){return Math.max(1,a-(new Date).getTime())};
var rv=function(a,b){document.cookie="G_ENABLED_IDPS="+a+";domain=."+b+";expires=Fri, 31 Dec 9999 12:00:00 GMT;path=/"},sv=function(){function a(){e[0]=1732584193;e[1]=4023233417;e[2]=2562383102;e[3]=271733878;e[4]=3285377520;n=m=0}function b(r){for(var u=g,q=0;64>q;q+=4)u[q/4]=r[q]<<24|r[q+1]<<16|r[q+2]<<8|r[q+3];for(q=16;80>q;q++)r=u[q-3]^u[q-8]^u[q-14]^u[q-16],u[q]=(r<<1|r>>>31)&4294967295;r=e[0];var v=e[1],t=e[2],w=e[3],z=e[4];for(q=0;80>q;q++){if(40>q)if(20>q){var x=w^v&(t^w);var B=1518500249}else x=
v^t^w,B=1859775393;else 60>q?(x=v&t|w&(v|t),B=2400959708):(x=v^t^w,B=3395469782);x=((r<<5|r>>>27)&4294967295)+x+z+B+u[q]&4294967295;z=w;w=t;t=(v<<30|v>>>2)&4294967295;v=r;r=x}e[0]=e[0]+r&4294967295;e[1]=e[1]+v&4294967295;e[2]=e[2]+t&4294967295;e[3]=e[3]+w&4294967295;e[4]=e[4]+z&4294967295}function c(r,u){if("string"===typeof r){r=unescape(encodeURIComponent(r));for(var q=[],v=0,t=r.length;v<t;++v)q.push(r.charCodeAt(v));r=q}u||(u=r.length);q=0;if(0==m)for(;q+64<u;)b(r.slice(q,q+64)),q+=64,n+=64;for(;q<
u;)if(f[m++]=r[q++],n++,64==m)for(m=0,b(f);q+64<u;)b(r.slice(q,q+64)),q+=64,n+=64}function d(){var r=[],u=8*n;56>m?c(k,56-m):c(k,64-(m-56));for(var q=63;56<=q;q--)f[q]=u&255,u>>>=8;b(f);for(q=u=0;5>q;q++)for(var v=24;0<=v;v-=8)r[u++]=e[q]>>v&255;return r}for(var e=[],f=[],g=[],k=[128],l=1;64>l;++l)k[l]=0;var m,n;a();return{reset:a,update:c,digest:d,Dg:function(){for(var r=d(),u="",q=0;q<r.length;q++)u+="0123456789ABCDEF".charAt(Math.floor(r[q]/16))+"0123456789ABCDEF".charAt(r[q]%16);return u}}},tv=
window.crypto,uv=!1,vv=0,wv=1,xv=0,yv="",zv=function(a){a=a||window.event;var b=a.screenX+a.clientX<<16;b+=a.screenY+a.clientY;b*=(new Date).getTime()%1E6;wv=wv*b%xv;if(3==++vv)if(a=window,b=zv,a.removeEventListener)a.removeEventListener("mousemove",b,!1);else if(a.detachEvent)a.detachEvent("onmousemove",b);else throw Error("R`mousemove");},Av=function(a){var b=sv();b.update(a);return b.Dg()};uv=!!tv&&"function"==typeof tv.getRandomValues;
uv||(xv=1E6*(screen.width*screen.width+screen.height),yv=Av(document.cookie+"|"+document.location+"|"+(new Date).getTime()+"|"+Math.random()),$u(window,"mousemove",zv));ev=ev||{};ev.xN="ssIFrame_";
_.Bv=function(a,b){this.Jb=a;if(!this.Jb)throw Error("S");a=_.hv(a,"idpIFrameUrl");if(!a)throw Error("T");this.$H=a;if(!b)throw Error("U");this.wk=b;a=this.$H;b=document.createElement("a");b.setAttribute("href",a);a=[b.protocol,"//",b.hostname];"http:"==b.protocol&&""!=b.port&&"0"!=b.port&&"80"!=b.port?(a.push(":"),a.push(b.port)):"https:"==b.protocol&&""!=b.port&&"0"!=b.port&&"443"!=b.port&&(a.push(":"),a.push(b.port));this.$z=a.join("");this.gY=[location.protocol,"//",location.host].join("");this.Zz=
this.nn=!1;this.WH=null;this.pv=[];this.Jn=[];this.li={};this.Bl=void 0};_.Bv.prototype.show=function(){var a=this.Bl;a.style.position="fixed";a.style.width="100%";a.style.height="100%";a.style.left="0px";a.style.top="0px";a.style.right="0px";a.style.bottom="0px";a.style.display="block";a.style.zIndex="9999999";a.style.overflow="hidden";a.setAttribute("aria-hidden","false")};_.Bv.prototype.Mc=function(){kv(this.Bl)};
_.Bv.prototype.Qu=function(a){if(this.nn)a&&a(this);else{if(!this.Bl){var b=ev.xN+this.Jb;var c=this.Jb;var d=location.hostname;var e,f=document.cookie.match("(^|;) ?G_ENABLED_IDPS=([^;]*)(;|$)");f&&2<f.length&&(e=f[2]);(f=e&&0<=Vu(e.split("|"),c))?rv(e,d):rv(e?e+"|"+c:c,d);c=!f;f=this.$H;var g=this.gY;d=this.wk;e=document.createElement("iframe");e.setAttribute("id",b);b="allow-scripts allow-same-origin";document.requestStorageAccess&&Xu(document.requestStorageAccess)&&(b+=" allow-storage-access-by-user-activation");
e.setAttribute("sandbox",b);kv(e);e.setAttribute("frame-border","0");b=[f,"#origin=",encodeURIComponent(g)];b.push("&rpcToken=");b.push(encodeURIComponent(d));c&&b.push("&clearCache=1");_.Tu&&b.push("&debug=1");document.body.appendChild(e);e.setAttribute("src",b.join(""));this.Bl=e}a&&this.pv.push(a)}};_.Bv.prototype.dl=function(){return this.WH};Cv=function(a){for(var b=0;b<a.pv.length;b++)a.pv[b](a);a.pv=[]};
_.Ev=function(a,b,c,d){if(a.nn){if(a.nn&&a.Zz)throw a="Failed to communicate with IDP IFrame due to unitialization error: "+a.dl(),Uu(a),Error(a);Dv(a,{method:b,params:c},d)}else a.Jn.push({rpc:{method:b,params:c},callback:d}),a.Qu()};Dv=function(a,b,c){if(c){for(var d=b.id;!d||a.li[d];)d=(new Date).getMilliseconds()+"-"+(1E6*Math.random()+1);b.id=d;a.li[d]=c}b.rpcToken=a.wk;a.Bl.contentWindow.postMessage(_.cv.stringify(b),a.$z)};Fv=function(a){if(a&&0<=a.indexOf("::"))throw Error("V");};
_.Bv.prototype.Hh=function(a,b,c,d,e,f,g,k){Fv(f);b=_.Yu(b);_.Ev(this,"getTokenResponse",{clientId:a,loginHint:c,request:b,sessionSelector:d,forceRefresh:g,skipCache:k,id:f},e)};_.Bv.prototype.Pu=function(a,b,c,d,e){b=_.Yu(b);_.Ev(this,"listIdpSessions",{clientId:a,request:b,sessionSelector:c,forceRefresh:e},d)};Gv=function(a,b,c){Fv(b.identifier);_.Ev(a,"getSessionSelector",b,c)};
_.Hv=function(a,b,c,d,e){Fv(b.identifier);_.Ev(a,"setSessionSelector",{domain:b.domain,crossSubDomains:b.crossSubDomains,policy:b.policy,id:b.id,hint:d,disabled:!!c},e)};Iv=function(a,b,c){_.Ev(a,"monitorClient",{clientId:b},c)};_.Bv.prototype.Xq=_.ka(29);_.Bv.prototype.iw=function(a,b){_.Ev(this,"showDialog",{W7:a},b)};_.Bv.prototype.Uo=_.ka(31);ev.mu={};ev.cz=function(a){return ev.mu[a]};
ev.Qu=function(a,b){var c=ev.cz(a);if(!c){c=String;if(uv){var d=new window.Uint32Array(1);tv.getRandomValues(d);d=Number("0."+d[0])}else d=wv,d+=parseInt(yv.substr(0,20),16),yv=Av(yv),d/=xv+Math.pow(16,20);c=c(2147483647*d);c=new _.Bv(a,c);ev.mu[a]=c}c.Qu(b)};ev.XR=function(a){for(var b in ev.mu){var c=ev.cz(b);if(c&&c.Bl&&c.Bl.contentWindow==a.source&&c.$z==a.origin)return c}};ev.GS=function(a){for(var b in ev.mu){var c=ev.cz(b);if(c&&c.$z==a)return c}};ev=ev||{};
var Kv=function(){var a=[],b;for(b in Jv)a.push(Jv[b]);dv.call(this,a);this.bk={};Uu("EventBus is ready.")};Wu(Kv,dv);var Jv={MO:"sessionSelectorChanged",Tw:"sessionStateChanged",Hw:"authResult",fN:"displayIFrame"},Mv=function(a){var b=Lv;a&&(b.bk[a]||(b.bk[a]=[]))},Nv=function(a,b,c){return b&&a.bk[b]&&0<=Vu(a.bk[b],c)};_.h=Kv.prototype;
_.h.oX=function(a){var b,c=!!a.source&&(a.source.opener===window||a.source===_.jv);if(b=c?ev.GS(a.origin):ev.XR(a)){try{var d=_.cv.parse(a.data)}catch(e){Uu("Bad event, an error happened when parsing data.");return}if(!c){if(!d||!d.rpcToken||d.rpcToken!=b.wk){Uu("Bad event, no RPC token.");return}if(d.id&&!d.method){c=d;if(a=b.li[c.id])delete b.li[c.id],a(c.result,c.error);return}}"fireIdpEvent"!=d.method?Uu("Bad IDP event, method unknown."):(a=d.params)&&a.type&&this.ZH[a.type]?(d=this.ZH[a.type],
c&&!d.xP?Uu("Bad IDP event. Source window cannot be a popup."):d.qo&&!d.qo.call(this,b,a)?Uu("Bad IDP event."):d.Ne.call(this,b,a)):Uu("Bad IDP event.")}else Uu("Bad event, no corresponding Idp Stub.")};_.h.KY=function(a,b){return Nv(this,a.Jb,b.clientId)};_.h.JY=function(a,b){b=b.clientId;return!b||Nv(this,a.Jb,b)};_.h.IP=function(a,b){return Nv(this,a.Jb,b.clientId)};_.h.zW=function(a){a.nn=!0;Cv(a);for(var b=0;b<a.Jn.length;b++)Dv(a,a.Jn[b].rpc,a.Jn[b].callback);a.Jn=[]};
_.h.yW=function(a,b){b={error:b.error};a.nn=!0;a.Zz=!0;a.WH=b;a.Jn=[];Cv(a)};_.h.Jv=function(a,b){b.originIdp=a.Jb;this.dispatchEvent(b)};var Lv=new Kv,Ov=Lv,Pv={};Pv.idpReady={Ne:Ov.zW};Pv.idpError={Ne:Ov.yW};Pv.sessionStateChanged={Ne:Ov.Jv,qo:Ov.KY};Pv.sessionSelectorChanged={Ne:Ov.Jv,qo:Ov.JY};Pv.authResult={Ne:Ov.Jv,qo:Ov.IP,xP:!0};Pv.displayIFrame={Ne:Ov.Jv};Lv.ZH=Pv||{};$u(window,"message",function(a){Lv.oX.call(Lv,a)});
_.Qv=function(a,b){this.$d=!1;if(!a)throw Error("W");var c=[],d;for(d in a)c.push(a[d]);dv.call(this,c);this.vd=[location.protocol,"//",location.host].join("");this.vc=b.crossSubDomains?b.domain||this.vd:this.vd;if(!b)throw Error("X");if(!b.idpId)throw Error("Y");if(!_.hv(b.idpId,"authServerUrl")||!_.hv(b.idpId,"idpIFrameUrl"))throw Error("Z`"+b.idpId);this.Jb=b.idpId;this.Ub=void 0;this.BQ=!!b.disableTokenRefresh;this.tR=!!b.forceTokenRefresh;this.MZ=!!b.skipTokenCache;this.setOptions(b);this.ep=
[];this.El=this.xI=!1;this.un=void 0;this.oK();this.Uc=void 0;var e=this,f=function(){Uu("Token Manager is ready.");if(e.ep.length)for(var g=0;g<e.ep.length;g++)e.ep[g].call(e);e.xI=!0;e.ep=[]};ev.Qu(this.Jb,function(g){e.Uc=g;g.nn&&g.Zz?(e.El=!0,e.un=g.dl(),e.lv(e.un)):e.Ub?Iv(e.Uc,e.Ub,function(k){if(k){k=e.Jb;var l=e.Ub,m=Lv;k&&l&&(m.bk[k]||(m.bk[k]=[]),0>Vu(m.bk[k],l)&&m.bk[k].push(l));f()}else e.un={error:"Not a valid origin for the client: "+e.vd+" has not been whitelisted for client ID "+e.Ub+
". Please go to https://console.developers.google.com/ and whitelist this origin for your project's client ID."},e.El=!0,e.lv(e.un)}):(Mv(e.Jb),f())})};Wu(_.Qv,dv);_.Qv.prototype.setOptions=function(){};_.Qv.prototype.oK=function(){};_.Qv.prototype.lv=function(){};_.Qv.prototype.dl=function(){return this.un};Rv=function(a,b,c){return function(){b.apply(a,c)}};_.Sv=function(a,b,c){if(a.xI)b.apply(a,c);else{if(a.El)throw a.un;a.ep.push(Rv(a,b,c))}};_.Qv.prototype.YE=_.ka(32);_.Qv.prototype.Uo=_.ka(30);
_.Uv=function(a,b){_.Qv.call(this,a,b);this.WJ=new lv;this.Pi=this.Ol=null;Tv(this)};Wu(_.Uv,_.Qv);_.Uv.prototype.setOptions=function(){};
var Vv=function(a,b){a.Zd={crossSubDomains:!!b.crossSubDomains,id:b.sessionSelectorId,domain:a.vc};b.crossSubDomains&&(a.Zd.policy=b.policy)},Wv=function(a,b){if(!b.authParameters)throw Error("$");if(!b.authParameters.scope)throw Error("aa");if(!b.authParameters.response_type)throw Error("ba");a.Ko=b.authParameters;a.Ko.redirect_uri||(a.Ko.redirect_uri=[location.protocol,"//",location.host,location.pathname].join(""));a.Ph=_.Yu(b.rpcAuthParameters||a.Ko);if(!a.Ph.scope)throw Error("ca");if(!a.Ph.response_type)throw Error("da");
a:{var c=a.Ph.response_type.split(" ");for(var d=0,e=c.length;d<e;d++)if(c[d]&&!av[c[d]]){c=!0;break a}c=!1}if(c)throw Error("ea");b.enableSerialConsent&&(a.Ph.enable_serial_consent=!0);b.authResultIdentifier&&(a.JP=b.authResultIdentifier);b.spec_compliant&&(a.Ph.spec_compliant=b.spec_compliant)};
_.Uv.prototype.oK=function(){var a=this;Lv.addEventListener(Jv.MO,function(b){a.$d&&a.Zd&&b.originIdp==a.Jb&&!b.crossSubDomains==!a.Zd.crossSubDomains&&b.domain==a.Zd.domain&&b.id==a.Zd.id&&a.IJ(b)});Lv.addEventListener(Jv.Tw,function(b){a.$d&&b.originIdp==a.Jb&&b.clientId==a.Ub&&a.JJ(b)});Lv.addEventListener(Jv.Hw,function(b){_.jv=void 0;a.$d&&b.originIdp==a.Jb&&b.clientId==a.Ub&&b.id==a.Mi&&(a.Ol&&(window.clearTimeout(a.Ol),a.Ol=null),a.Mi=void 0,a.Fq(b))});Lv.addEventListener(Jv.fN,function(b){a.$d&&
b.originIdp==a.Jb&&(b.Mc?a.Uc.Mc():a.Uc.show())})};_.Uv.prototype.IJ=function(){};_.Uv.prototype.JJ=function(){};_.Uv.prototype.Fq=function(){};var Yv=function(a,b){Xv(a);a.BQ||(a.Pi=fv.uQ(function(){a.Hh(!0)},b-3E5),navigator.onLine&&a.Pi.start())},Xv=function(a){a.Pi&&(a.Pi.clear(),a.Pi=null)},Tv=function(a){var b=window;bv()&&(b=document.body);$u(b,"online",function(){a.Pi&&a.Pi.start()});$u(b,"offline",function(){a.Pi&&a.Pi.clear()})};_.h=_.Uv.prototype;_.h.Hh=function(){};
_.h.iw=function(a,b){this.Uc.iw(a,b)};_.h.rJ=_.ka(33);_.h.LV=function(a,b){if(!this.Ub)throw Error("ia");this.Uc.Pu(this.Ub,this.Ph,this.Zd,a,b)};_.h.Pu=function(a,b){_.Sv(this,this.LV,[a,b])};_.$v=function(a){this.Wd=void 0;this.Eg=!1;this.Vn=void 0;_.Uv.call(this,_.Zv,a)};Wu(_.$v,_.Uv);_.Zv={VD:"noSessionBound",Co:"userLoggedOut",LM:"activeSessionChanged",Tw:"sessionStateChanged",hP:"tokenReady",gP:"tokenFailed",Hw:"authResult",ERROR:"error"};
_.$v.prototype.setOptions=function(a){if(!a.clientId)throw Error("ja");this.Ub=a.clientId;this.Ca=a.id;Vv(this,a);Wv(this,a)};_.$v.prototype.lv=function(a){this.dispatchEvent({type:_.Zv.ERROR,error:"idpiframe_initialization_failed",details:a.error,idpId:this.Jb})};var aw=function(a){Xv(a);a.Vn=void 0;a.BA=void 0};_.h=_.$v.prototype;
_.h.IJ=function(a){var b=a.newValue||{};if(this.Wd!=b.hint||this.Eg!=!!b.disabled){a=this.Wd;var c=!this.Wd||this.Eg;aw(this);this.Wd=b.hint;this.Eg=!!b.disabled;(b=!this.Wd||this.Eg)&&!c?this.dispatchEvent({type:_.Zv.Co,idpId:this.Jb}):b||(a!=this.Wd&&this.dispatchEvent({type:_.Zv.LM,idpId:this.Jb}),this.Wd&&this.Hh())}};
_.h.JJ=function(a){this.Eg||(this.Wd?a.user||this.Vn?a.user==this.Wd&&(this.Vn?a.sessionState?this.Vn=a.sessionState:(aw(this),this.dispatchEvent({type:_.Zv.Co,idpId:this.Jb})):a.sessionState&&(this.Vn=a.sessionState,this.Hh())):this.Hh():this.dispatchEvent({type:_.Zv.Tw,idpId:this.Jb}))};_.h.Fq=function(a){this.dispatchEvent({type:_.Zv.Hw,authResult:a.authResult})};_.h.Jp=_.ka(35);_.h.Cp=function(a){_.Sv(this,this.Py,[a])};_.h.Py=function(a){Gv(this.Uc,this.Zd,a)};
_.h.jw=function(a,b,c){if(!a)throw Error("ka");aw(this);this.Wd=a;this.Eg=!1;b&&_.Hv(this.Uc,this.Zd,!1,this.Wd);this.$d=!0;this.Hh(c,!0)};_.h.start=function(){_.Sv(this,this.RZ,[])};
_.h.RZ=function(){var a=this.Ub==Zu("client_id")?Zu("login_hint"):void 0;var b=this.Ub==Zu("client_id")?Zu("state"):void 0;this.aB=b;if(a)window.history.replaceState?window.history.replaceState(null,document.title,window.location.href.split("#")[0]):window.location.href.hash="",this.jw(a,!0,!0);else{var c=this;this.Cp(function(d){c.$d=!0;d&&d.hint?(aw(c),c.Wd=d.hint,c.Eg=!!d.disabled,c.Eg?c.dispatchEvent({type:_.Zv.Co,idpId:c.Jb}):c.jw(d.hint)):(aw(c),c.Wd=void 0,c.Eg=!(!d||!d.disabled),c.dispatchEvent({type:_.Zv.VD,
autoOpenAuthUrl:!c.Eg,idpId:c.Jb}))})}};_.h.uG=_.ka(36);_.h.Hh=function(a,b){var c=this;this.Uc.Hh(this.Ub,this.Ph,this.Wd,this.Zd,function(d,e){(e=e||d.error)?"user_logged_out"==e?(aw(c),c.dispatchEvent({type:_.Zv.Co,idpId:c.Jb})):(c.BA=null,c.dispatchEvent({type:_.Zv.gP,idpId:c.Jb,error:e})):(c.BA=d,c.Vn=d.session_state,Yv(c,d.expires_at),d.idpId=c.Jb,b&&c.aB&&(d.state=c.aB,c.aB=void 0),c.dispatchEvent({type:_.Zv.hP,idpId:c.Jb,response:d}))},this.Ca,a)};_.h.Xq=_.ka(28);_.h.EK=_.ka(37);
_.bw=function(a){this.Jk=null;_.Uv.call(this,{},a);this.$d=!0};Wu(_.bw,_.Uv);_.h=_.bw.prototype;_.h.setOptions=function(a){if(!a.clientId)throw Error("ja");this.Ub=a.clientId;this.Ca=a.id;Vv(this,a);Wv(this,a)};_.h.lv=function(a){this.Jk&&(this.Jk({authResult:{error:"idpiframe_initialization_failed",details:a.error}}),this.Jk=null)};_.h.Fq=function(a){if(this.Jk){var b=this.Jk;this.Jk=null;b(a)}};_.h.Jp=_.ka(34);_.h.Cp=function(a){this.El?a(this.dl()):_.Sv(this,this.Py,[a])};
_.h.Py=function(a){Gv(this.Uc,this.Zd,a)};_.cw=function(a,b,c){a.El?c(a.dl()):_.Sv(a,a.PW,[b,c])};_.bw.prototype.PW=function(a,b){this.Uc.Hh(this.Ub,this.Ph,a,this.Zd,function(c,d){d?b({error:d}):b(c)},this.Ca,this.tR,this.MZ)};_.bw.prototype.TI=_.ka(38);

var dw,fw,gw,hw,iw,jw,kw,lw,mw,nw,ow,rw;dw=function(a){return Array.prototype.concat.apply([],arguments)};_.ew=function(){try{var a=Array.from((window.crypto||window.msCrypto).getRandomValues(new Uint8Array(64)))}catch(c){a=[];for(var b=0;64>b;b++)a[b]=Math.floor(256*Math.random())}return _.ih(a,3).substring(0,64)};fw=function(a,b,c){if(!a.$d)throw Error("fa");b?_.Hv(a.Uc,a.Zd,!0,void 0,c):_.Hv(a.Uc,a.Zd,!0,a.Wd,c)};gw=function(a){if(!a.$d)throw Error("fa");return a.BA};
_.bw.prototype.TI=_.Sc(38,function(a,b){var c=this.Uc,d=this.Ub,e=this.Zd,f=_.Yu(this.Ph);delete f.response_type;_.Ev(c,"getOnlineCode",{clientId:d,loginHint:a,request:f,sessionSelector:e},b)});_.$v.prototype.EK=_.Sc(37,function(a){gw(this)&&gw(this).access_token&&(this.Uc.Xq(this.Ub,gw(this).access_token,a),fw(this,!0))});_.$v.prototype.uG=_.Sc(36,function(){var a=this;this.Cp(function(b){b&&b.hint?b.disabled?a.dispatchEvent({type:_.Zv.Co,idpId:a.Jb}):a.Hh(!0):a.dispatchEvent({type:_.Zv.VD,idpId:a.Jb})})});
_.$v.prototype.Jp=_.Sc(35,function(){var a=this;return function(b){b&&b.authResult&&b.authResult.login_hint&&a.jw(b.authResult.login_hint,a.Eg||b.authResult.login_hint!=a.Wd,!0)}});
_.bw.prototype.Jp=_.Sc(34,function(a){var b=this;return function(c){c&&c.authResult&&c.authResult.login_hint?b.Cp(function(d){_.Hv(b.Uc,b.Zd,d&&d.disabled,c.authResult.login_hint,function(){_.cw(b,c.authResult.login_hint,a)})}):a(c&&c.authResult&&c.authResult.error?c.authResult:c&&c.authResult&&!c.authResult.login_hint?{error:"wrong_response_type"}:{error:"unknown_error"})}});_.Uv.prototype.rJ=_.Sc(33,function(){this.Ub&&_.Ev(this.Uc,"startPolling",{clientId:this.Ub,origin:this.vd,id:this.Mi},void 0)});
_.Bv.prototype.Xq=_.Sc(29,function(a,b,c){_.Ev(this,"revoke",{clientId:a,token:b},c)});_.$v.prototype.Xq=_.Sc(28,function(a){_.Sv(this,this.EK,[a])});hw=function(){var a=navigator.userAgent,b;if(b=!!a&&-1!=a.indexOf("CriOS"))b=-1,(a=a.match(/CriOS\/(\d+)/))&&a[1]&&(b=parseInt(a[1],10)||-1),b=48>b;return b};
iw=function(){var a=navigator.userAgent.toLowerCase();if(!(-1<a.indexOf("safari/")&&0>a.indexOf("chrome/")&&0>a.indexOf("crios/")&&0>a.indexOf("android")))return!1;var b=/version\/(\d+)\.(\d+)[\.0-9]*/.exec(navigator.userAgent.toLowerCase());if(!b||3>b.length)return!1;a=parseInt(b[1],10);b=parseInt(b[2],10);return 12<a||12==a&&1<=b};
jw=function(a,b,c,d,e,f,g){var k=_.hv(a,"authServerUrl");if(!k)throw Error("P`"+a);a=_.Yu(d);a.response_type=g||"permission";a.client_id=c;a.ss_domain=b;if(f&&f.extraQueryParams)for(var l in f.extraQueryParams)a[l]=f.extraQueryParams[l];(b=e)&&!(b=iw())&&(b=navigator.userAgent.toLowerCase(),-1<b.indexOf("ipad;")||-1<b.indexOf("iphone;")?(b=/os (\d+)_\d+(_\d+)? like mac os x/.exec(navigator.userAgent.toLowerCase()),b=!b||2>b.length?!1:14<=parseInt(b[1],10)):b=!1);b&&!a.prompt&&(a.prompt="select_account");
k+=0>k.indexOf("?")?"?":"&";b=[];for(var m in a)if(a.hasOwnProperty(m)){c=a[m];if(null===c||void 0===c)c="";b.push(encodeURIComponent(m)+"="+encodeURIComponent(c))}return k+b.join("&")};
kw=function(a,b,c,d){if(!a.Ub)throw Error("ga");a.Mi=c||a.JP||"auth"+Math.floor(1E6*Math.random()+1);b=b||{};b.extraQueryParams=b.extraQueryParams||{};if(!b.extraQueryParams.redirect_uri){var e=a.vd.split("//");c=b.extraQueryParams;var f=e[0],g=f.indexOf(":");0<g&&(f=f.substring(0,g));e=["storagerelay://",f,"/",e[1],"?"];e.push("id="+a.Mi);c.redirect_uri=e.join("")}return jw(a.Jb,a.vc,a.Ub,a.Ko,!0,b,d)};
lw=function(a,b){a.Ol&&window.clearTimeout(a.Ol);a.Ol=window.setTimeout(function(){a.Mi==b&&(_.jv=void 0,a.Ol=null,a.Mi=void 0,a.Fq({authResult:{error:"popup_closed_by_user"}}))},1E3)};mw=function(a,b,c){if(!a.Ub)throw Error("ha");c=c||{};c=kw(a,c.sessionMeta,c.oneTimeId,c.responseType);(Object.hasOwnProperty.call(window,"ActiveXObject")&&!window.ActiveXObject||hw())&&_.Sv(a,a.rJ,[]);var d=a.Mi;a.WJ.open(c,b,function(){a.Mi==d&&lw(a,d)},function(){a.Mi=void 0;a.Fq({authResult:{error:"popup_blocked_by_browser"}})})};
nw=function(a){_.Sv(a,a.uG,[])};ow=function(a,b,c){a.El?c(a.dl()):_.Sv(a,a.TI,[b,c])};
_.pw=function(a){for(var b=[],c=0,d=0;c<a.length;){var e=a[c++];if(128>e)b[d++]=String.fromCharCode(e);else if(191<e&&224>e){var f=a[c++];b[d++]=String.fromCharCode((e&31)<<6|f&63)}else if(239<e&&365>e){f=a[c++];var g=a[c++],k=a[c++];e=((e&7)<<18|(f&63)<<12|(g&63)<<6|k&63)-65536;b[d++]=String.fromCharCode(55296+(e>>10));b[d++]=String.fromCharCode(56320+(e&1023))}else f=a[c++],g=a[c++],b[d++]=String.fromCharCode((e&15)<<12|(f&63)<<6|g&63)}return b.join("")};
_.qw=function(a,b){function c(l){for(;d<a.length;){var m=a.charAt(d++),n=_.fh[m];if(null!=n)return n;if(!_.Le(m))throw Error("v`"+m);}return l}_.hh();for(var d=0;;){var e=c(-1),f=c(0),g=c(64),k=c(64);if(64===k&&-1===e)break;b(e<<2|f>>4);64!=g&&(b(f<<4&240|g>>2),64!=k&&b(g<<6&192|k))}};rw=function(a){var b=[];_.qw(a,function(c){b.push(c)});return b};_.sw=function(a,b){_.Lh[b||"token"]=a};_.tw=function(a){delete _.Lh[a||"token"]};
_.cv={parse:function(a){a=_.xf("["+String(a)+"]");if(!1===a||1!==a.length)throw new SyntaxError("JSON parsing failed.");return a[0]},stringify:function(a){return _.yf(a)}};
_.bw.prototype.Cy=function(a,b){_.Sv(this,this.fR,[a,b])};_.bw.prototype.fR=function(a,b){this.Uc.Cy(this.Ub,a,this.Ph,this.Zd,b)};
_.Bv.prototype.Cy=function(a,b,c,d,e){c=_.Yu(c);_.Ev(this,"gsi:fetchLoginHint",{clientId:a,loginHint:b,request:c,sessionSelector:d},e)};
var uw,vw=["client_id","cookie_policy","scope"],ww="client_id cookie_policy fetch_basic_profile hosted_domain scope openid_realm disable_token_refresh login_hint ux_mode redirect_uri state prompt oidc_spec_compliant nonce enable_serial_consent include_granted_scopes response_type session_selection gsiwebsdk".split(" "),xw=["authuser","after_redirect","access_type","hl"],yw=["login_hint","prompt"],zw={clientid:"client_id",cookiepolicy:"cookie_policy"},Aw=["approval_prompt","authuser","login_hint",
"prompt","hd"],Bw=["login_hint","g-oauth-window","status"],Cw=Math.min(_.R("oauth-flow/authWindowWidth",599),screen.width-20),Dw=Math.min(_.R("oauth-flow/authWindowHeight",600),screen.height-30);
var Ew=function(a){_.Tc.call(this,a)};_.hi(Ew,_.Tc);Ew.prototype.name="gapi.auth2.ExternallyVisibleError";
var Fw=function(){};Fw.prototype.select=function(a,b){if(a.sessions&&1==a.sessions.length&&(a=a.sessions[0],a.login_hint)){b(a);return}b()};var Gw=function(){};Gw.prototype.select=function(a,b){if(a.sessions&&a.sessions.length)for(var c=0;c<a.sessions.length;c++){var d=a.sessions[c];if(d.login_hint){b(d);return}}b()};var Hw=function(a){this.KP=a};
Hw.prototype.select=function(a,b){if(a.sessions)for(var c=0;c<a.sessions.length;c++){var d=a.sessions[c];if(d.session_state&&d.session_state.extraQueryParams&&d.session_state.extraQueryParams.authuser==this.KP){d.login_hint?b(d):b();return}}b()};
var Iw=function(a){this.Kd=a;this.Tv=[]};Iw.prototype.select=function(a){var b=0,c=this,d=function(e){if(e)a(e);else{var f=c.Tv[b];f?(b++,c.Kd.Pu(function(g){g?f.select(g,d):d()})):a()}};d()};var Jw=function(a){a=new Iw(a);a.Tv.push(new Fw);return a},Kw=function(a){a=new Iw(a);a.Tv.push(new Gw);return a},Lw=function(a,b){void 0===b||null===b?b=Jw(a):(a=new Iw(a),a.Tv.push(new Hw(b)),b=a);return b};
var Mw=function(a){this.Ne=a;this.Ud=!0};Mw.prototype.remove=function(){this.Ud=!1};Mw.prototype.trigger=function(){};var Nw=function(a){this.remove=function(){a.remove()};this.trigger=function(){a.trigger()}},Ow=function(){this.Xb=[]};Ow.prototype.add=function(a){this.Xb.push(a)};Ow.prototype.notify=function(a){for(var b=this.Xb,c=[],d=0;d<b.length;d++){var e=b[d];e.Ud&&(c.push(e),_.uk(Pw(e.Ne,a)))}this.Xb=c};var Pw=function(a,b){return function(){a(b)}};
var Rw=function(a){this.ee=null;this.I_=new Qw(this);this.Xb=new Ow;void 0!=a&&this.set(a)};Rw.prototype.set=function(a){a!=this.ee&&(this.ee=a,this.I_.value=a,this.Xb.notify(this.ee))};Rw.prototype.get=function(){return this.ee};Rw.prototype.V=function(a){a=new Sw(this,a);this.Xb.add(a);return a};var Sw=function(a,b){Mw.call(this,b);this.OV=a};_.hi(Sw,Mw);Sw.prototype.trigger=function(){var a=this.Ne;a(this.OV.get())};var Qw=function(a){this.value=null;this.V=function(b){return new Nw(a.V(b))}};
var Tw={X1:"fetch_basic_profile",d3:"login_hint",D4:"prompt",K4:"redirect_uri",b5:"scope",r6:"ux_mode",O5:"state"},Uw=function(a){this.Ba={};if(a&&!_.ri(a))if("function"==typeof a.get)this.Ba=a.get();else for(var b in Tw){var c=Tw[b];c in a&&(this.Ba[c]=a[c])}};Uw.prototype.get=function(){return this.Ba};Uw.prototype.yL=function(a){this.Ba.scope=a;return this};Uw.prototype.Wp=function(){return this.Ba.scope};
var Vw=function(a,b){var c=a.Ba.scope;b=dw(b.split(" "),c?c.split(" "):[]);_.Je(b);a.Ba.scope=b.join(" ")};_.h=Uw.prototype;_.h.qZ=function(a){this.Ba.prompt=a;return this};_.h.KS=function(){return this.Ba.prompt};_.h.NY=function(){_.Ef("Property app_package_name no longer supported and was not set");return this};_.h.zR=function(){_.Ef("Property app_package_name no longer supported")};_.h.Fe=function(a){this.Ba.state=a};_.h.getState=function(){return this.Ba.state};
var Ww=function(){return["toolbar=no","location="+(window.opera?"no":"yes"),"directories=no,status=no,menubar=no,scrollbars=yes,resizable=yes,copyhistory=no","width="+Cw,"height="+Dw,"top="+(screen.height-Dw)/2,"left="+(screen.width-Cw)/2].join()},Xw=function(a){a=a&&a.id_token;if(!a||!a.split(".")[1])return null;a=(a.split(".")[1]+"...").replace(/^((....)+).?.?.?$/,"$1");return JSON.parse(_.pw(rw(a)))},Yw=function(){uw=_.R("auth2/idpValue","google");var a=_.R("oauth-flow/authUrl","https://accounts.google.com/o/oauth2/auth"),
b=_.R("oauth-flow/idpIframeUrl","https://accounts.google.com/o/oauth2/iframe");_.iv(uw,{authServerUrl:a,idpIFrameUrl:b})},Zw=function(a,b,c){for(var d=0;d<b.length;d++){var e=b[d];if(d===b.length-1){a[e]=c;break}_.Ya(a[e])||(a[e]={});a=a[e]}},$w=function(){var a=window.location.origin;a||(a=window.location.protocol+"//"+window.location.host);return a};
var ax=function(a){var b=a?(b=Xw(a))?b.sub:null:null;this.Ca=b;this.uc=a?_.jk(a):null};_.h=ax.prototype;_.h.ma=function(){return this.Ca};_.h.Zy=function(){var a=Xw(this.uc);return a?a.hd:null};_.h.zf=function(){return!!this.uc};_.h.Oj=function(a){if(a)return this.uc;a=bx;var b=_.jk(this.uc);!a.wu||a.Uz||a.tU||(delete b.access_token,delete b.scope);return b};_.h.FB=function(){return bx.FB()};_.h.hj=function(){this.uc=null};_.h.fS=function(){return this.uc?this.uc.scope:null};
_.h.update=function(a){this.Ca=a.Ca;this.uc=a.uc;this.uc.id_token?this.Es=new cx(this.uc):this.Es&&(this.Es=null)};var dx=function(a){return a.uc&&"object"==typeof a.uc.session_state?_.jk(a.uc.session_state.extraQueryParams||{}):{}};_.h=ax.prototype;_.h.zp=function(){var a=dx(this);return a&&void 0!==a.authuser&&null!==a.authuser?a.authuser:null};
_.h.fj=function(a){var b=bx,c=new Uw(a);b.Uz=c.Wp()?!0:!1;bx.wu&&Vw(c,"openid profile email");return new _.Ek(function(d,e){var f=dx(this);f.login_hint=this.ma();f.scope=c.Wp();ex(b,d,e,f)},this)};_.h.Yp=function(a){return new _.Ek(function(b,c){var d=a||{},e=bx;d.login_hint=this.ma();e.Yp(d).then(b,c)},this)};_.h.eT=function(a){return this.fj(a)};_.h.disconnect=function(){return bx.disconnect()};_.h.DR=function(){return this.Es};
_.h.iu=function(a){if(!this.zf())return!1;var b=this.uc&&this.uc.scope?this.uc.scope.split(" "):"";return _.pb(a?a.split(" "):[],function(c){return _.Xa(b,c)})};var cx=function(a){a=Xw(a);this.wR=a.sub;this.sd=a.name;this.bT=a.given_name;this.dR=a.family_name;this.fI=a.picture;this.kt=a.email};_.h=cx.prototype;_.h.ma=function(){return this.wR};_.h.getName=function(){return this.sd};_.h.dS=function(){return this.bT};_.h.ZR=function(){return this.dR};_.h.oS=function(){return this.fI};_.h.Kt=function(){return this.kt};
var gx=function(a,b,c){this.Jl=b;this.lW=a;for(var d in a)a.hasOwnProperty(d)&&fx(this,d);if(c&&c.length)for(a=0;a<c.length;a++)this[c[a]]=this.Jl[c[a]]},fx=function(a,b){a[b]=function(){return a.lW[b].apply(a.Jl,arguments)}};gx.prototype.then=function(a,b,c){var d=this;return _.Ik().then(function(){return hx(d.Jl,a,b,c)})};_.nk(gx);
var ix;ix=function(a){var b=location;if(a&&"none"!=a)return"single_host_origin"==a?b.protocol+"//"+b.host:a};
_.jx=function(a){if(!a)throw new Ew("No cookiePolicy");var b=window.location.hostname;"single_host_origin"==a&&(a=window.location.protocol+"//"+b);if("none"==a)return null;var c=/^(https?:\/\/)([0-9.\-_A-Za-z]+)(?::(\d+))?$/.exec(a);if(!c)throw new Ew("Invalid cookiePolicy");a=c[2];c=c[1];var d={};d.dotValue=a.split(".").length;d.isSecure=-1!=c.indexOf("https");d.domain=a;if(!_.pi(b,"."+a)&&!_.pi(b,a))throw new Ew("Invalid cookiePolicy domain");return d};
var lx,kx,mx,nx,ox,px,rx,wx,sx,yx,zx,tx;lx=function(a){var b=a||{},c=kx();_.lb(ww,function(d){"undefined"===typeof b[d]&&"undefined"!==typeof c[d]&&(b[d]=c[d])});return b};kx=function(){for(var a={},b=document.getElementsByTagName("meta"),c=0;c<b.length;++c)if(b[c].name){var d=b[c].name;if(0==d.indexOf("google-signin-")){d=d.substring(14);var e=b[c].content;zw[d]&&(d=zw[d]);_.Xa(ww,d)&&e&&(a[d]="true"==e?!0:"false"==e?!1:e)}}return a};
mx=function(a){return String(a).replace(/_([a-z])/g,function(b,c){return c.toUpperCase()})};nx=function(a){_.lb(ww,function(b){var c=mx(b);"undefined"!==typeof a[c]&&"undefined"===typeof a[b]&&(a[b]=a[c],delete a[c])})};ox=function(a){a=lx(a);nx(a);a.cookie_policy||(a.cookie_policy="single_host_origin");var b=ww+xw,c;for(c in a)0>b.indexOf(c)&&delete a[c];return a};
px=function(a,b){if(!a)throw new Ew("Empty initial options.");for(var c=0;c<vw.length;++c)if(!(b&&"scope"==vw[c]||a[vw[c]]))throw new Ew("Missing required parameter '"+vw[c]+"'");_.jx(a.cookie_policy)};
rx=function(a){var b={authParameters:{redirect_uri:void 0,response_type:"token id_token",scope:a.scope,"openid.realm":a.openid_realm},clientId:a.client_id,crossSubDomains:!0,domain:ix(a.cookie_policy),disableTokenRefresh:!!a.disable_token_refresh,idpId:uw};_.qx(b,a);_.lb(yw,function(c){a[c]&&(b.authParameters[c]=a[c])});"boolean"==typeof a.enable_serial_consent&&(b.enableSerialConsent=a.enable_serial_consent);return b};_.qx=function(){};
wx=function(a){var b=a.client_id,c=a.cookie_policy,d=a.scope,e=a.openid_realm,f=a.hosted_domain,g=a.oidc_spec_compliant,k=a.nonce,l=sx(a),m={authParameters:{response_type:l,scope:d,"openid.realm":e},rpcAuthParameters:{response_type:l,scope:d,"openid.realm":e},clientId:b,crossSubDomains:!0,domain:ix(c),idpId:uw};f&&(m.authParameters.hd=f,m.rpcAuthParameters.hd=f);g&&(m.rpcAuthParameters.spec_compliant=g,k=k||_.ew());k&&(m.authParameters.nonce=k,m.rpcAuthParameters.nonce=k,m.forceTokenRefresh=!0,m.skipTokenCache=
!0);_.lb(yw.concat(xw),function(n){a[n]&&(m.authParameters[n]=a[n])});void 0!==a.authuser&&null!==a.authuser&&(m.authParameters.authuser=a.authuser);"boolean"==typeof a.include_granted_scopes&&(b=new tx(a.response_type||"token"),ux(b)&&(m.authParameters.include_granted_scopes=a.include_granted_scopes),vx(b)&&(m.rpcAuthParameters.include_granted_scopes=a.include_granted_scopes,!1===a.include_granted_scopes&&(m.forceTokenRefresh=!0,m.skipTokenCache=!0)));"boolean"==typeof a.enable_serial_consent&&(m.enableSerialConsent=
a.enable_serial_consent);return m};sx=function(a){a=new tx(a.response_type||"token");var b=[];vx(a)&&b.push("token");xx(a,"id_token")&&b.push("id_token");0==b.length&&(b=["token","id_token"]);return b.join(" ")};yx=["permission","id_token"];zx=/(^|[^_])token/;tx=function(a){this.Pn=[];this.kA(a)};
tx.prototype.kA=function(a){a?((0<=a.indexOf("permission")||a.match(zx))&&this.Pn.push("permission"),0<=a.indexOf("id_token")&&this.Pn.push("id_token"),0<=a.indexOf("code")&&this.Pn.push("code")):this.Pn=yx};var ux=function(a){return xx(a,"code")},vx=function(a){return xx(a,"permission")};tx.prototype.toString=function(){return this.Pn.join(" ")};var xx=function(a,b){var c=!1;_.lb(a.Pn,function(d){d==b&&(c=!0)});return c};
var bx,Ax,Cx,Ex,Fx,hx;bx=null;_.Bx=function(){return bx?Ax():null};Ax=function(){return new gx(Cx.prototype,bx,["currentUser","isSignedIn"])};Cx=function(a){delete a.include_granted_scopes;this.Ba=rx(a);this.qQ=a.cookie_policy;this.tU=!!a.scope;(this.wu=!1!==a.fetch_basic_profile)&&(this.Ba.authParameters.scope=Dx(this,"openid profile email"));this.kq=a.hosted_domain;this.F_=a.ux_mode||"popup";this.uX=a.redirect_uri||null;Ex(this)};
Ex=function(a){a.currentUser=new Rw(new ax(null));a.isSignedIn=new Rw(!1);a.Kd=new _.$v(a.Ba);a.xn=null;a.Du=null;a.BV=new _.Ek(function(b,c){this.xn=b;this.Du=c},a);a.ov={};a.uq=!0;Fx(a);a.Kd.start()};
Fx=function(a){a.Kd.addEventListener("error",function(b){a.uq&&a.xn&&(a.uq=!1,a.Du({error:b.error,details:b.details}),a.xn=null,a.Du=null)});a.Kd.addEventListener("authResult",function(b){b&&b.authResult&&a.Ke(b);a.Kd.Jp()(b)});a.Kd.addEventListener("tokenReady",function(b){var c=new ax(b.response);if(a.kq&&a.kq!=c.Zy())a.Ke({type:"tokenFailed",reason:"Account domain does not match hosted_domain specified by gapi.auth2.init.",accountDomain:c.Zy(),expectedDomain:a.kq});else{a.currentUser.get().update(c);
var d=a.currentUser;d.Xb.notify(d.ee);a.isSignedIn.set(!0);c=c.zp();(d=_.jx(a.qQ))&&c&&_.Dh.set(["G_AUTHUSER_","https:"===window.location.protocol&&d.xe?"S":"H",d.kh].join(""),c,{domain:d.domain,secure:d.isSecure});_.sw(b.response);a.Ke(b)}});a.Kd.addEventListener("noSessionBound",function(b){a.uq&&b.autoOpenAuthUrl?(a.uq=!1,Jw(a.Kd).select(function(c){if(c&&c.login_hint){var d=a.Kd;_.Sv(d,d.jw,[c.login_hint,!0])}else a.currentUser.set(new ax(null)),a.isSignedIn.set(!1),_.tw(),a.Ke(b)})):(a.currentUser.set(new ax(null)),
a.isSignedIn.set(!1),_.tw(),a.Ke(b))});a.Kd.addEventListener("tokenFailed",function(b){a.Ke(b)});a.Kd.addEventListener("userLoggedOut",function(b){a.currentUser.get().hj();var c=a.currentUser;c.Xb.notify(c.ee);a.isSignedIn.set(!1);_.tw();a.Ke(b)})};hx=function(a,b,c,d){return a.BV.then(function(e){if(b)return b(e.cT)},c,d)};Cx.prototype.Ke=function(a){if(a){this.uq=!1;var b=a.type||"";if(this.ov[b])this.ov[b](a);this.xn&&(this.xn({cT:this}),this.Du=this.xn=null)}};
var Gx=function(a,b){_.zb(b,function(c,d){a.ov[d]=function(e){a.ov={};c(e)}})},ex=function(a,b,c,d){d=_.jk(d);a.kq&&(d.hd=a.kq);var e=d.ux_mode||a.F_;delete d.ux_mode;delete d.app_package_name;var f={sessionMeta:{extraQueryParams:d},responseType:"permission id_token"};"redirect"==e?(d.redirect_uri||(d.redirect_uri=a.uX||$w()+window.location.pathname),Hx(a,f)):(delete d.redirect_uri,Ix(a,f),Gx(a,{authResult:function(g){g.authResult&&g.authResult.error?c(g.authResult):Gx(a,{tokenReady:function(){b(a.currentUser.get())},
tokenFailed:c})}}))};Cx.prototype.fj=function(a){return new _.Ek(function(b,c){var d=new Uw(a);this.Uz=d.Wp()?!0:!1;this.wu?(d.Ba.fetch_basic_profile=!0,Vw(d,"email profile openid")):d.Ba.fetch_basic_profile=!1;var e=Dx(this,d.Wp());d.yL(e);ex(this,b,c,d.get())},this)};
Cx.prototype.Yp=function(a){var b=a||{};this.Uz=!!b.scope;a=Dx(this,b.scope);if(""==a)return _.Jk({error:"Missing required parameter: scope"});var c={scope:a,access_type:"offline",include_granted_scopes:!0};_.lb(Aw,function(d){null!=b[d]&&(c[d]=b[d])});c.hasOwnProperty("prompt")||c.hasOwnProperty("approval_prompt")||(c.prompt="consent");return"postmessage"==b.redirect_uri||void 0==b.redirect_uri?Jx(this,c):Kx(this,c,b.redirect_uri)};
var Kx=function(a,b,c){b.redirect_uri=c;Hx(a,{sessionMeta:{extraQueryParams:b},responseType:"code id_token"});return _.Ik({message:"Redirecting to IDP."})},Jx=function(a,b){b.origin=$w();delete b.redirect_uri;Ix(a,{sessionMeta:{extraQueryParams:b},responseType:"code permission id_token"});return new _.Ek(function(c,d){Gx(this,{authResult:function(e){(e=e&&e.authResult)&&e.code?c({code:e.code}):d(e&&e.error?e:{error:"unknown_error"})}})},a)},Ix=function(a,b){Zw(b,["sessionMeta","extraQueryParams",
"gsiwebsdk"],"2");mw(a.Kd,Ww(),b)},Hx=function(a,b){Zw(b,["sessionMeta","extraQueryParams","gsiwebsdk"],"2");var c=b||{};b=window.location;var d=b.assign;a=a.Kd;if(!a.Ub)throw Error("ga");a=jw(a.Jb,a.vc,a.Ub,a.Ko,!1,c.sessionMeta,c.responseType);d.call(b,a)};Cx.prototype.hj=function(a){var b=a||!1;return new _.Ek(function(c){fw(this.Kd,b,function(){c()})},this)};Cx.prototype.SG=function(){return this.Ba.authParameters.scope};
var Dx=function(a,b){a=a.SG();b=dw(b?b.split(" "):[],a?a.split(" "):[]);_.Je(b);return b.join(" ")};Cx.prototype.FB=function(){var a=this;return new _.Ek(function(b,c){Gx(a,{noSessionBound:c,tokenFailed:c,userLoggedOut:c,tokenReady:function(d){b(d.response)}});nw(a.Kd)})};
Cx.prototype.GP=function(a,b,c,d){if(a="string"===typeof a?document.getElementById(a):a){var e=this;_.Pi(a,"click",function(){var f=b;"function"==typeof b&&(f=b());e.fj(f).then(function(g){c&&c(g)},function(g){d&&d(g)})})}else d&&d({error:"Could not attach click handler to the element. Reason: element not found."})};Cx.prototype.disconnect=function(){return new _.Ek(function(a){this.Kd.Xq(function(){a()})},this)};
var Lx;_.Ek.prototype["catch"]=_.Ek.prototype.Lr;Lx=null;_.Mx=function(a){a=ox(a);if(bx){if(_.ik(a,Lx||{}))return Ax();throw new Ew("gapi.auth2 has been initialized with different options. Consider calling gapi.auth2.getAuthInstance() instead of gapi.auth2.init().");}px(a,!1!==a.fetch_basic_profile);Yw();Lx=a;bx=new Cx(a);_.ye.ga=1;return Ax()};
var Ox,Qx,Nx,Sx,Rx,Tx;_.Px=function(a,b){Yw();a=ox(a);px(a);var c=wx(a),d=new _.bw(c);"none"==a.prompt?Nx(d,a,function(e){e.status=e.error?{signed_in:!1,method:null,google_logged_in:!1}:{signed_in:!0,method:"AUTO",google_logged_in:!0};b(e)}):Ox(d,a,function(e){if(e.error)e.status={signed_in:!1,method:null,google_logged_in:!1};else{var f=e.access_token||e.id_token;e.status={signed_in:!!f,method:"PROMPT",google_logged_in:!!f}}e["g-oauth-window"]=d.WJ.Sg;b(e)})};
Ox=function(a,b,c){var d=new tx(b.response_type);c=Qx(a,d,c);var e={responseType:d.toString()};Zw(e,["sessionMeta","extraQueryParams","gsiwebsdk"],b.gsiwebsdk||"2");ux(d)&&Zw(e,["sessionMeta","extraQueryParams","access_type"],b.access_type||"offline");b.redirect_uri&&Zw(e,["sessionMeta","extraQueryParams","redirect_uri"],b.redirect_uri);b.state&&Zw(e,["sessionMeta","extraQueryParams","state"],b.state);b=Ww();a.El?c({authResult:{error:"idpiframe_initialization_failed",details:a.dl().error}}):(a.Jk=
c,mw(a,b,e))};Qx=function(a,b,c){if(vx(b)){var d=Rx(c);return function(e){e&&e.authResult&&!e.authResult.error?a.Jp(function(f){f&&!f.error?(f=_.jk(f),ux(b)&&(f.code=e.authResult.code),d(f)):d(f?f:{error:"unknown_error"})})(e):d(e&&e.authResult?e.authResult:{error:"unknown_error"})}}return function(e){e&&e.authResult&&!e.authResult.error?c(_.jk(e.authResult)):c(e&&e.authResult?e.authResult:{error:"unknown_error"})}};
Nx=function(a,b,c){if(ux(new tx(b.response_type))&&"offline"==b.access_type)c({error:"immediate_failed",error_subtype:"access_denied"});else{var d=Rx(c);b.login_hint?a.Cy(b.login_hint,function(e){e?Sx(a,b,e,d):c({error:"immediate_failed",error_subtype:"access_denied"})}):void 0!==b.authuser&&null!==b.authuser?Lw(a,b.authuser).select(function(e){e&&e.login_hint?Sx(a,b,e.login_hint,d):d({error:"immediate_failed",error_subtype:"access_denied"})}):a.Cp(function(e){e&&e.hint?Sx(a,b,e.hint,d):e&&e.disabled?
d({error:"immediate_failed",error_subtype:"no_user_bound"}):("first_valid"==b.session_selection?Kw(a):Jw(a)).select(function(f){f&&f.login_hint?Sx(a,b,f.login_hint,d):d({error:"immediate_failed",error_subtype:"no_user_bound"})})})}};Sx=function(a,b,c,d){b=new tx(b.response_type);var e=0,f={},g=function(k){!k||k.error?d(k):(e--,_.Bb(f,k),0==e&&d(f))};(vx(b)||xx(b,"id_token"))&&e++;ux(b)&&e++;(vx(b)||xx(b,"id_token"))&&_.cw(a,c,g);ux(b)&&ow(a,c,g)};
Rx=function(a){return function(b){if(!b||b.error)_.tw(),b?a(b):a({error:"unknown_error"});else{if(b.access_token){var c=_.jk(b);Tx(c);delete c.id_token;delete c.code;_.sw(c)}a(b)}}};Tx=function(a){_.lb(Bw,function(b){delete a[b]})};
_.K("gapi.auth2.init",_.Mx);_.K("gapi.auth2.authorize",function(a,b){if(null!=bx)throw new Ew("gapi.auth2.authorize cannot be called after GoogleAuth has been initialized (i.e. with a call to gapi.auth2.init, or gapi.client.init when given a 'clientId' and a 'scope' parameters).");_.Px(a,function(c){Tx(c);b(c)})});_.K("gapi.auth2._gt",function(){return _.Mh()});_.K("gapi.auth2.enableDebugLogs",function(a){a=!1!==a;_.Tu="0"!=a&&!!a});_.K("gapi.auth2.getAuthInstance",_.Bx);
_.K("gapi.auth2.BasicProfile",cx);_.K("gapi.auth2.BasicProfile.prototype.getId",cx.prototype.ma);_.K("gapi.auth2.BasicProfile.prototype.getName",cx.prototype.getName);_.K("gapi.auth2.BasicProfile.prototype.getGivenName",cx.prototype.dS);_.K("gapi.auth2.BasicProfile.prototype.getFamilyName",cx.prototype.ZR);_.K("gapi.auth2.BasicProfile.prototype.getImageUrl",cx.prototype.oS);_.K("gapi.auth2.BasicProfile.prototype.getEmail",cx.prototype.Kt);_.K("gapi.auth2.GoogleAuth",Cx);
_.K("gapi.auth2.GoogleAuth.prototype.attachClickHandler",Cx.prototype.GP);_.K("gapi.auth2.GoogleAuth.prototype.disconnect",Cx.prototype.disconnect);_.K("gapi.auth2.GoogleAuth.prototype.grantOfflineAccess",Cx.prototype.Yp);_.K("gapi.auth2.GoogleAuth.prototype.signIn",Cx.prototype.fj);_.K("gapi.auth2.GoogleAuth.prototype.signOut",Cx.prototype.hj);_.K("gapi.auth2.GoogleAuth.prototype.getInitialScopes",Cx.prototype.SG);_.K("gapi.auth2.GoogleUser",ax);_.K("gapi.auth2.GoogleUser.prototype.grant",ax.prototype.eT);
_.K("gapi.auth2.GoogleUser.prototype.getId",ax.prototype.ma);_.K("gapi.auth2.GoogleUser.prototype.isSignedIn",ax.prototype.zf);_.K("gapi.auth2.GoogleUser.prototype.getAuthResponse",ax.prototype.Oj);_.K("gapi.auth2.GoogleUser.prototype.getBasicProfile",ax.prototype.DR);_.K("gapi.auth2.GoogleUser.prototype.getGrantedScopes",ax.prototype.fS);_.K("gapi.auth2.GoogleUser.prototype.getHostedDomain",ax.prototype.Zy);_.K("gapi.auth2.GoogleUser.prototype.grantOfflineAccess",ax.prototype.Yp);
_.K("gapi.auth2.GoogleUser.prototype.hasGrantedScopes",ax.prototype.iu);_.K("gapi.auth2.GoogleUser.prototype.reloadAuthResponse",ax.prototype.FB);_.K("gapi.auth2.LiveValue",Rw);_.K("gapi.auth2.LiveValue.prototype.listen",Rw.prototype.V);_.K("gapi.auth2.LiveValue.prototype.get",Rw.prototype.get);_.K("gapi.auth2.SigninOptionsBuilder",Uw);_.K("gapi.auth2.SigninOptionsBuilder.prototype.getAppPackageName",Uw.prototype.zR);_.K("gapi.auth2.SigninOptionsBuilder.prototype.setAppPackageName",Uw.prototype.NY);
_.K("gapi.auth2.SigninOptionsBuilder.prototype.getScope",Uw.prototype.Wp);_.K("gapi.auth2.SigninOptionsBuilder.prototype.setScope",Uw.prototype.yL);_.K("gapi.auth2.SigninOptionsBuilder.prototype.getPrompt",Uw.prototype.KS);_.K("gapi.auth2.SigninOptionsBuilder.prototype.setPrompt",Uw.prototype.qZ);_.K("gapi.auth2.SigninOptionsBuilder.prototype.get",Uw.prototype.get);

_.qx=function(a,b){var c=b.oidc_spec_compliant;b=b.nonce;c&&(a.spec_compliant=c,b=b||_.ew());b&&(a.authParameters.nonce=b,a.forceTokenRefresh=!0,a.skipTokenCache=!0)};

_.Eh=function(){function a(){e[0]=1732584193;e[1]=4023233417;e[2]=2562383102;e[3]=271733878;e[4]=3285377520;n=m=0}function b(r){for(var u=g,q=0;64>q;q+=4)u[q/4]=r[q]<<24|r[q+1]<<16|r[q+2]<<8|r[q+3];for(q=16;80>q;q++)r=u[q-3]^u[q-8]^u[q-14]^u[q-16],u[q]=(r<<1|r>>>31)&4294967295;r=e[0];var v=e[1],t=e[2],w=e[3],z=e[4];for(q=0;80>q;q++){if(40>q)if(20>q){var x=w^v&(t^w);var B=1518500249}else x=v^t^w,B=1859775393;else 60>q?(x=v&t|w&(v|t),B=2400959708):(x=v^t^w,B=3395469782);x=((r<<5|r>>>27)&4294967295)+
x+z+B+u[q]&4294967295;z=w;w=t;t=(v<<30|v>>>2)&4294967295;v=r;r=x}e[0]=e[0]+r&4294967295;e[1]=e[1]+v&4294967295;e[2]=e[2]+t&4294967295;e[3]=e[3]+w&4294967295;e[4]=e[4]+z&4294967295}function c(r,u){if("string"===typeof r){r=unescape(encodeURIComponent(r));for(var q=[],v=0,t=r.length;v<t;++v)q.push(r.charCodeAt(v));r=q}u||(u=r.length);q=0;if(0==m)for(;q+64<u;)b(r.slice(q,q+64)),q+=64,n+=64;for(;q<u;)if(f[m++]=r[q++],n++,64==m)for(m=0,b(f);q+64<u;)b(r.slice(q,q+64)),q+=64,n+=64}function d(){var r=[],
u=8*n;56>m?c(k,56-m):c(k,64-(m-56));for(var q=63;56<=q;q--)f[q]=u&255,u>>>=8;b(f);for(q=u=0;5>q;q++)for(var v=24;0<=v;v-=8)r[u++]=e[q]>>v&255;return r}for(var e=[],f=[],g=[],k=[128],l=1;64>l;++l)k[l]=0;var m,n;a();return{reset:a,update:c,digest:d,Dg:function(){for(var r=d(),u="",q=0;q<r.length;q++)u+="0123456789ABCDEF".charAt(Math.floor(r[q]/16))+"0123456789ABCDEF".charAt(r[q]%16);return u}}};
var Gh=function(a,b,c){var d=[],e=[];if(1==(Array.isArray(c)?2:1))return e=[b,a],_.lb(d,function(k){e.push(k)}),Fh(e.join(" "));var f=[],g=[];_.lb(c,function(k){g.push(k.key);f.push(k.value)});c=Math.floor((new Date).getTime()/1E3);e=0==f.length?[c,b,a]:[f.join(":"),c,b,a];_.lb(d,function(k){e.push(k)});a=Fh(e.join(" "));a=[c,a];0==g.length||a.push(g.join(""));return a.join("_")},Fh=function(a){var b=_.Eh();b.update(a);return b.Dg().toLowerCase()};
_.Hh=function(){var a=_.C.__SAPISID||_.C.__APISID||_.C.__OVERRIDE_SID;if(a)return!0;a=new _.Bh(document);a=a.get("SAPISID")||a.get("APISID")||a.get("__Secure-3PAPISID")||a.get("SID");return!!a};
_.Ih=function(a){var b=_.qg(String(_.C.location.href));if(_.Hh()){var c=(b=0==b.indexOf("https:")||0==b.indexOf("chrome-extension:")||0==b.indexOf("moz-extension:"))?_.C.__SAPISID:_.C.__APISID;c||(c=new _.Bh(document),c=c.get(b?"SAPISID":"APISID")||c.get("__Secure-3PAPISID"));if(c){b=b?"SAPISIDHASH":"APISIDHASH";var d=String(_.C.location.href);return d&&c&&b?[b,Gh(_.qg(d),c,a||null)].join(" "):null}}return null};

_.Jh=function(a){var b={SAPISIDHASH:!0,APISIDHASH:!0};return a&&(a.OriginToken||a.Authorization&&b[String(a.Authorization).split(" ")[0]])?!0:!1};_.Kh={IH:_.Jh,vV:_.Hh,XG:function(){var a=null;_.Hh()&&(a=window.__PVT,null==a&&(a=(new _.Bh(document)).get("BEAT")));return a},yG:_.Ih};

_.Re.R1=function(a){var b=[];if(1<arguments.length)for(var c=0,d;d=arguments[c];++c)b.push(d);else b=a;return function(e){for(var f=0;b[f];++f)if(e===b[f])return!0;return!1}};_.Re.Y4=function(a){return function(b){return a.test(b)}};_.Re.mN=function(a){return"undefined"!==typeof a};_.Re.Y3=function(a){return"string"===typeof a&&0<a.length};_.Re.p0=function(a){return"boolean"===typeof a};_.Re.i3=function(a){return function(b){for(var c in a)if(a.hasOwnProperty(c)&&!(0,a[c])(b[c]))return!1;return!0}};

_.Ne=_.Ne||{};
(function(){function a(b){var c="";if(3==b.nodeType||4==b.nodeType)c=b.nodeValue;else if(b.innerText)c=b.innerText;else if(b.innerHTML)c=b.innerHTML;else if(b.firstChild){c=[];for(b=b.firstChild;b;b=b.nextSibling)c.push(a(b));c=c.join("")}return c}_.Ne.createElement=function(b){if(!document.body||document.body.namespaceURI)try{var c=document.createElementNS("http://www.w3.org/1999/xhtml",b)}catch(d){}return c||document.createElement(b)};_.Ne.createIframeElement=function(b){var c=_.Ne.createElement("iframe");try{var d=
["<","iframe"],e=b||{},f;for(f in e)e.hasOwnProperty(f)&&(d.push(" "),d.push(f),d.push('="'),d.push(_.Ne.escapeString(e[f])),d.push('"'));d.push("></");d.push("iframe");d.push(">");var g=_.Ne.createElement(d.join(""));g&&(!c||g.tagName==c.tagName&&g.namespaceURI==c.namespaceURI)&&(c=g)}catch(l){}d=c;b=b||{};for(var k in b)b.hasOwnProperty(k)&&(d[k]=b[k]);return c};_.Ne.getBodyElement=function(){if(document.body)return document.body;try{var b=document.getElementsByTagNameNS("http://www.w3.org/1999/xhtml",
"body");if(b&&1==b.length)return b[0]}catch(c){}return document.documentElement||document};_.Ne.v8=function(b){return a(b)}})();

_.Ne=_.Ne||{};(function(){function a(d){b=d["core.util"]||{}}var b={},c={};_.Re&&_.Re.register("core.util",null,a);_.Ne.getFeatureParameters=function(d){return"undefined"===typeof b[d]?null:b[d]};_.Ne.hasFeature=function(d){return"undefined"!==typeof b[d]};_.Ne.H8=function(){return c}})();

/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
_.fy=function(a,b,c){if("function"===typeof a)c&&(a=(0,_.P)(a,c));else if(a&&"function"==typeof a.handleEvent)a=(0,_.P)(a.handleEvent,a);else throw Error("oa");return 2147483647<Number(b)?-1:_.C.setTimeout(a,b||0)};_.gy=function(a){_.C.clearTimeout(a)};_.hy=function(a){var b=null;return(new _.Ek(function(c,d){b=_.fy(function(){c(void 0)},a);-1==b&&d(Error("pa"))})).Lr(function(c){_.gy(b);throw c;})};

/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
_.Gz=function(a){this.n_=a};_.Gz.prototype.toString=function(){return this.n_};
_.Hz=function(a){_.si.call(this);this.Gh=1;this.Av=[];this.Fv=0;this.Ye=[];this.Xh={};this.FP=!!a};_.O(_.Hz,_.si);_.h=_.Hz.prototype;_.h.subscribe=function(a,b,c){var d=this.Xh[a];d||(d=this.Xh[a]=[]);var e=this.Gh;this.Ye[e]=a;this.Ye[e+1]=b;this.Ye[e+2]=c;this.Gh=e+3;d.push(e);return e};_.h.Hr=_.ka(40);_.h.unsubscribe=function(a,b,c){if(a=this.Xh[a]){var d=this.Ye;if(a=_.gi(a,function(e){return d[e+1]==b&&d[e+2]==c}))return this.nj(a)}return!1};
_.h.nj=function(a){var b=this.Ye[a];if(b){var c=this.Xh[b];0!=this.Fv?(this.Av.push(a),this.Ye[a+1]=_.Za):(c&&_.ni(c,a),delete this.Ye[a],delete this.Ye[a+1],delete this.Ye[a+2])}return!!b};
_.h.In=function(a,b){var c=this.Xh[a];if(c){for(var d=Array(arguments.length-1),e=1,f=arguments.length;e<f;e++)d[e-1]=arguments[e];if(this.FP)for(e=0;e<c.length;e++){var g=c[e];Iz(this.Ye[g+1],this.Ye[g+2],d)}else{this.Fv++;try{for(e=0,f=c.length;e<f;e++)g=c[e],this.Ye[g+1].apply(this.Ye[g+2],d)}finally{if(this.Fv--,0<this.Av.length&&0==this.Fv)for(;c=this.Av.pop();)this.nj(c)}}return 0!=e}return!1};var Iz=function(a,b,c){_.Ck(function(){a.apply(b,c)})};
_.Hz.prototype.clear=function(a){if(a){var b=this.Xh[a];b&&(_.lb(b,this.nj,this),delete this.Xh[a])}else this.Ye.length=0,this.Xh={}};_.Hz.prototype.Fb=function(a){if(a){var b=this.Xh[a];return b?b.length:0}a=0;for(b in this.Xh)a+=this.Fb(b);return a};_.Hz.prototype.va=function(){_.Hz.T.va.call(this);this.clear();this.Av.length=0};
_.Jz=function(a){_.si.call(this);this.Gd=new _.Hz(a);_.vi(this,this.Gd)};_.O(_.Jz,_.si);_.h=_.Jz.prototype;_.h.subscribe=function(a,b,c){return this.Gd.subscribe(a.toString(),b,c)};_.h.Hr=_.ka(39);_.h.unsubscribe=function(a,b,c){return this.Gd.unsubscribe(a.toString(),b,c)};_.h.nj=function(a){return this.Gd.nj(a)};_.h.In=function(a,b){return this.Gd.In(a.toString(),b)};_.h.clear=function(a){this.Gd.clear(void 0!==a?a.toString():void 0)};
_.h.Fb=function(a){return this.Gd.Fb(void 0!==a?a.toString():void 0)};

/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
_.Kz=function(a,b){Array.isArray(b)||(b=[b]);b=_.nb(b,function(c){return"string"===typeof c?c:c.Dv+" "+c.duration+"s "+c.timing+" "+c.delay+"s"});_.Kr(a,"transition",b.join(","))};
_.Lz=_.Gb(function(){if(_.rc)return _.Nc("10.0");var a=_.Wd("DIV"),b=_.vc?"-webkit":_.uc?"-moz":_.rc?"-ms":_.qc?"-o":null,c={transition:"opacity 1s linear"};b&&(c[b+"-transition"]="opacity 1s linear");b=_.xr("div",{style:c});_.Cd(a,b);a=a.firstChild;b=a.style[_.yr("transition")];return""!=("undefined"!==typeof b?b:a.style[_.Jr(a,"transition")]||"")});

_.Nz=!1;_.Oz=function(){_.Mz="oauth2relay"+String(2147483647*(0,_.tg)()|0)};_.Pz=new _.Jz;_.Qz=new _.Gz("oauth");_.Oz();_.R("oauth-flow/client_id");var Rz=String(_.R("oauth-flow/redirectUri"));if(Rz)Rz.replace(/[#][\s\S]*/,"");else{var Sz=_.og.getOrigin(window.location.href);_.R("oauth-flow/callbackUrl");encodeURIComponent(Sz)}_.og.getOrigin(window.location.href);

_.Nz=!0;

var Uz,Vz,Wz,Xz,Yz,Zz,$z,aA,bA,cA,dA,fA,gA,hA,iA,jA,kA,lA,mA,nA,oA,pA,qA,rA,sA,tA,uA,vA,wA,xA,yA,zA,AA,BA,CA,DA,EA,FA,GA,HA,IA,JA,MA,LA,NA,OA,PA,QA,RA,SA,UA,VA,XA;_.Tz=function(a,b){if(_.gh&&!b)return _.C.atob(a);var c="";_.qw(a,function(d){c+=String.fromCharCode(d)});return c};Uz=function(a){var b=String(a("immediate")||"");a=String(a("prompt")||"");return"true"===b||"none"===a};Vz=function(a){return _.yh("enableMultilogin")&&a("cookie_policy")&&!Uz(a)?!0:!1};
Yz=function(){var a,b=null;_.yz.iterate(function(c,d){0===c.indexOf("G_AUTHUSER_")&&(c=_.Qy(c.substring(11)),!a||c.xe&&!a.xe||c.xe==a.xe&&c.kh>a.kh)&&(a=c,b=d)});return{PP:a,authuser:b}};Zz=[".APPS.GOOGLEUSERCONTENT.COM","@DEVELOPER.GSERVICEACCOUNT.COM"];$z=function(a){a=a.toUpperCase();for(var b=0,c=Zz.length;b<c;++b){var d=a.split(Zz[b]);2==d.length&&""===d[1]&&(a=d[0])}a=a.replace(/-/g,"_").toUpperCase();40<a.length&&(b=new _.Qh,b.yw(a),a=b.Dg().toUpperCase());return a};
aA=function(a){if(!a)return[];a=a.split("=");return a[1]?a[1].split("|"):[]};bA=function(a){a=a.split(":");return{clientId:a[0].split("=")[1],LY:aA(a[1]),k9:aA(a[2]),i8:aA(a[3])}};cA=function(a){var b=Yz(),c=b.PP;b=b.authuser;var d=a&&$z(a);if(null!==b){var e;_.yz.iterate(function(g,k){(g=_.Sy(g))&&g.uA&&(d&&g.hQ!=d||g.xe==c.xe&&g.kh==c.kh&&(e=k))});if(e){var f=bA(e);a=f&&f.LY[Number(b)];f=f&&f.clientId;if(a)return{authuser:b,b$:a,clientId:f}}}return null};
dA=function(a,b){a=_.Mh(a);if(!a||!b&&a.error)return null;b=Math.floor((new Date).getTime()/1E3);return a.expires_at&&b>a.expires_at?null:a};_.eA=function(a,b){if(b){var c=b;var d=a}else"string"===typeof a?d=a:c=a;c?_.sw(c,d):_.tw(d)};
fA=function(a){if(!a)return null;"single_host_origin"!==a&&(a=_.qg(a));var b=window.location.hostname,c=b,d=_.Ry;if("single_host_origin"!==a){c=a.split("://");if(2==c.length)d="https"===c.shift();else return _.Cf("WARNING invalid cookie_policy: "+a),null;c=c[0]}if(-1!==c.indexOf(":"))c=b="";else{a="."+c;if(b.lastIndexOf(a)!==b.length-a.length)return _.Cf("Invalid cookie_policy domain: "+c),null;c=a;b=c.split(".").length-1}return{domain:c,xe:d,kh:b}};
gA=function(a){var b=fA(a);if(!b)return new _.Wy("G_USERSTATE_");a=["G_USERSTATE_",_.Ry&&b.xe?"S":"H",b.kh].join("");var c=_.Cz[a];c||(c={$I:63072E3},_.oe(_.Fz(b),c),c=new _.Ty(a,c),_.Cz[a]=c,b=c.read(),"undefined"!==typeof b&&null!==b&&(document.cookie=a+"=; expires=Thu, 01 Jan 1970 00:00:01 GMT; path=/",c.write(b)));return c};hA=function(a){var b=gA(a).read();a=_.me();if(b){b=b.split(":");for(var c;c=b.shift();)c=c.split("="),a[c[0]]=c[1]}return a};
iA=function(a,b,c){var d=hA(b),e=d[a];d[a]="0";var f=[];_.Wl(d,function(k,l){f.push(l+"="+k)});var g=f.join(":");b=gA(b);g?b.write(g):b.clear();d[a]!==e&&c&&c()};jA=function(a,b){b=hA(b);return"0"==b[a]||"X"==b[a]};kA=function(a){a=fA(a.g_user_cookie_policy);if(!a||a.xe&&!_.Ry)a=null;else{var b=["G_AUTHUSER_",_.Ry&&a.xe?"S":"H",a.kh].join(""),c=_.Bz[b];c||(c=new _.yz(b,_.Fz(a)),_.Bz[b]=c);a=c}_.Ge("googleapis.config/sessionIndex",null);a.clear()};lA=function(a){return Uz(function(b){return a[b]})};
mA=0;nA=!1;oA=[];pA={};qA={};rA=null;sA=function(a){var b=_.Mz;return function(c){if(this.f==b&&this.t==_.Jf.getAuthToken(this.f)&&this.origin==_.Jf.getTargetOrigin(this.f))return a.apply(this,arguments)}};tA=function(a){"function"===typeof a.setAttribute?a.setAttribute("aria-hidden","true"):a["aria-hidden"]="true"};uA=function(a){if(_.Nz&&a&&!decodeURIComponent(a).startsWith("m;/_/scs/"))throw Error("sa");};
vA=function(a){var b=_.Ne.getUrlParameters,c=b(a).jsh;if(null!=c)return uA(c),a;if(b=String(b().jsh||_.ye.h||""))uA(b),c=(a+"#").indexOf("#"),a=a.substr(0,c)+(-1!==a.substr(0,c).indexOf("?")?"&":"?")+"jsh="+encodeURIComponent(b)+a.substr(c);return a};wA=function(){return!!_.R("oauth-flow/usegapi")};xA=function(a,b){wA()?rA.unregister(a):_.Jf.unregister(a+":"+b)};yA=function(a,b,c){wA()?rA.register(a,c,_.Cm):_.Jf.register(a+":"+b,sA(c))};zA=function(){Wz.parentNode.removeChild(Wz)};
AA=function(a){var b=Wz;_.Kz(b,[{Dv:"-webkit-transform",duration:1,timing:"ease",delay:0}]);_.Kz(b,[{Dv:"transform",duration:1,timing:"ease",delay:0}]);_.fy(function(){b.style.webkitTransform="translate3d(0px,"+a+"px,0px)";b.style.transform="translate3d(0px,"+a+"px,0px)"},0)};BA=function(){var a=Xz+88;AA(a);Xz=a};CA=function(){var a=Xz-88;AA(a);Xz=a};
DA=function(a){var b=a?BA:CA,c=a?CA:BA;a=a?"-":"";Xz=parseInt(a+88,10);Wz.style.webkitTransform="translate3d(0px,"+a+88+"px,0px)";Wz.style.transform="translate3d(0px,"+a+88+"px,0px)";Wz.style.display="";Wz.style.visibility="visible";b();_.fy(c,4E3);_.fy(zA,5E3)};
EA=function(a){var b=_.R("oauth-flow/toast/position");"top"!==b&&(b="bottom");var c=document.createElement("div");Wz=c;c.style.cssText="position:fixed;left:0px;z-index:1000;width:100%;";_.Kr(c,"visibility","hidden");_.Kr(c,b,"-40px");_.Kr(c,"height","128px");var d=c;if("desktop"==_.R("deviceType")){d=document.createElement("div");d.style.cssText="float:left;position:relative;left:50%;";c.appendChild(d);var e=document.createElement("div");e.style.cssText="float:left;position:relative;left:-50%";d.appendChild(e);
d=e}e="top"==b?"-":"";Xz=parseInt(e+88,10);Wz.style.webkitTransform="translate3d(0px,"+e+88+"px,0px)";Wz.style.transform="translate3d(0px,"+e+88+"px,0px)";e=window;try{for(;e.parent!=e&&e.parent.document;)e=e.parent}catch(f){}e=e.document.body;try{e.insertBefore(c,e.firstChild)}catch(f){}_.Xl.Jh({url:":socialhost:/:session_prefix:_/widget/oauthflow/toast",queryParams:{clientId:a.client_id,idToken:a.id_token},where:d,onRestyle:function(){"top"===b?DA(!0):DA(!1)}})};
FA=function(a){var b=_.on(),c=b&&b.scope;b=a&&a.scope;b="string"===typeof b?b.split(" "):b||[];if(c){c=c.split(" ");for(var d=0;d<c.length;++d){var e=c[d];-1==_.tj.call(b,e)&&b.push(e)}0<b.length&&(a.scope=b.join(" "))}return a};
GA=function(a,b){var c=null;a&&b&&(c=b.client_id=b.client_id||a.client_id,b.scope=b.scope||a.scope,b.g_user_cookie_policy=a.cookie_policy,b.cookie_policy=b.cookie_policy||a.cookie_policy,b.response_type=b.response_type||a.response_type);if(b){b.issued_at||(b.issued_at=String(Math.floor((new Date).getTime()/1E3)));var d=parseInt(b.expires_in,10)||86400;b.error&&(d=_.R("oauth-flow/errorMaxAge")||86400);b.expires_in=String(d);b.expires_at||(b.expires_at=String(Math.floor((new Date).getTime()/1E3)+d));
b._aa||b.error||null!=cA(c)||!lA(a)||(b._aa="1");a=b.status={};a.google_logged_in=!!b.session_state;c=a.signed_in=!!b.access_token;a.method=c?b["g-oauth-window"]?"PROMPT":"AUTO":null}return b};HA=function(a){a=a&&a.id_token;if(!a||!a.split(".")[1])return null;a=(a.split(".")[1]+"...").replace(/^((....)+)\.?\.?\.?$/,"$1");a=_.xf(_.Tz(a,!0));if(!1===a)throw Error("ta");return a};IA=function(a){return(a=HA(a))?a.sub:null};
JA=function(a){a&&oA.push(a);a=_.Mz;var b=document.getElementById(a),c=(new Date).getTime();if(b){if(mA&&6E4>c-mA)return;var d=_.Jf.getAuthToken(a);d&&(xA("oauth2relayReady",d),xA("oauth2callback",d));b.parentNode.removeChild(b);if(/Firefox/.test(navigator.userAgent))try{window.frames[a]=void 0}catch(f){}_.Oz();a=_.Mz}mA=c;var e=String(2147483647*(0,_.tg)()|0);b=_.R("oauth-flow/proxyUrl")||_.R("oauth-flow/relayUrl");wA()?rA=_.Xl.Jh({where:_.Ne.getBodyElement(),url:b,id:a,attributes:{style:{width:"1px",
height:"1px",position:"absolute",top:"-100px",display:"none"},"aria-hidden":"true"},dontclear:!0}):(b=[b,"?parent=",encodeURIComponent(_.og.getOrigin(window.location.href)),"#rpctoken=",e,"&forcesecure=1"].join(""),c=_.Ne.getBodyElement(),d=_.Ne.createIframeElement({name:a,id:a}),d.src=vA(b),d.style.width="1px",d.style.height="1px",d.style.position="absolute",d.style.top="-100px",d.tabIndex=-1,tA(d),c.appendChild(d),_.Jf.setupReceiver(a));yA("oauth2relayReady",e,function(){xA("oauth2relayReady",e);
var f=oA;if(null!==f){oA=null;for(var g=0,k=f.length;g<k;++g)f[g]()}});yA("oauth2callback",e,function(f){var g=_.Ne.getUrlParameters;g=g(f);var k=g.state;f=k.replace(/\|.*$/,"");f={}.hasOwnProperty.call(qA,f)?qA[f]:null;g.state=f;if(null!=g.state){f=pA[k];delete pA[k];k=f&&f.key||"token";var l=g=GA(f&&f.params,g);var m=(m=IA(l))?jA(m,l.cookie_policy):!1;!m&&l&&0<=(" "+(l.scope||"")+" ").indexOf(" https://www.googleapis.com/auth/plus.login ")&&_.R("isLoggedIn")&&"1"===(l&&l._aa)&&(l._aa="0",nA||(nA=
!0,EA(l)));_.eA(k,g);g=dA(k);if(f){k=f.popup;l=f.after_redirect;if(k&&"keep_open"!=l)try{k.close()}catch(n){}f.callback&&(f.callback(g),f.callback=null)}}})};_.KA=function(a){null!==oA?JA(a):a&&a()};MA=function(a,b){var c=LA,d=IA(a);d&&(kA(a),iA(d,b,function(){if(c){var e={error:"user_signed_out"};e.client_id=a.client_id;e.g_user_cookie_policy=a.g_user_cookie_policy;e.scope=a.scope;e.response_type=a.response_type;e.session_state=a.session_state;e=GA(null,e);c(e)}}))};
LA=function(a){a||(a=dA(void 0,!0));a&&"object"===typeof a||(a={error:"invalid_request",error_description:"no callback data"});var b=a.error_description;b&&window.console&&(window.console.error(a.error),window.console.error(b));a.error||(_.ye.drw=null);_.eA(a);if(b=a.authuser)_.R("googleapis.config/sessionIndex"),_.Ge("googleapis.config/sessionIndex",b);_.Pz.In(_.Qz,a);return a};NA=["client_id","cookie_policy","response_type"];OA="client_id response_type login_hint authuser prompt include_granted_scopes after_redirect access_type hl state".split(" ");
PA=function(a){var b=_.jk(a);b.session_state&&b.session_state.extraQueryParams&&(b.authuser=b.session_state.extraQueryParams.authuser);b.session_state=null;a.expires_at&&(b.expires_at=parseInt(a.expires_at/1E3).toString());a.expires_in&&(b.expires_in=a.expires_in.toString());a.first_issued_at&&(b.issued_at=parseInt(a.first_issued_at/1E3).toString(),delete b.first_issued_at);_.sw(b);return b};
QA=function(a){if(void 0===a.include_granted_scopes){var b=_.R("include_granted_scopes");a.include_granted_scopes=!!b}};RA=function(a){window.console&&("function"===typeof window.console.warn?window.console.warn(a):"function"===typeof window.console.log&&window.console.log(a))};
SA=function(a){var b=a||{},c={};_.lb(OA,function(d){null!=b[d]&&(c[d]=b[d])});a=_.R("googleapis/overrideClientId");null!=a&&(c.client_id=a);QA(c);"string"===typeof b.scope?c.scope=b.scope:Array.isArray(b.scope)&&(c.scope=b.scope.join(" "));null!=b["openid.realm"]&&(c.openid_realm=b["openid.realm"]);null!=b.cookie_policy?c.cookie_policy=b.cookie_policy:null!=b.cookiepolicy&&(c.cookie_policy=b.cookiepolicy);null==c.login_hint&&null!=b.user_id&&(c.login_hint=b.user_id);try{_.jx(c.cookie_policy)}catch(d){c.cookie_policy&&
RA("The cookie_policy configuration: '"+c.cookie_policy+"' is illegal, and thus ignored."),delete c.cookie_policy}null!=b.hd&&(c.hosted_domain=b.hd);null==c.prompt&&(1==b.immediate||"true"==b.immediate?c.prompt="none":"force"==b.approval_prompt&&(c.prompt="consent"));"none"==c.prompt&&(c.session_selection="first_valid");"none"==c.prompt&&"offline"==c.access_type&&delete c.access_type;"undefined"===typeof c.authuser&&(a=_.Ah(),null!=a&&(c.authuser=a));a=b.redirect_uri||_.R("oauth-flow/redirectUri");
null!=a&&"postmessage"!=a&&(c.redirect_uri=a);c.gsiwebsdk="shim";return c};
_.TA=function(a,b){var c=SA(a),d=new _.Ek(function(e,f){_.Px(c,function(g){var k=g||{};_.lb(NA,function(l){null==k[l]&&(k[l]=c[l])});!c.include_granted_scopes&&a&&a.scope&&(k.scope=a.scope);a&&null!=a.state&&(k.state=a.state);k.error?("none"==c.prompt&&"user_logged_out"==k.error&&(k.error="immediate_failed_user_logged_out"),f(k)):(g=PA(k),null!=g.authuser&&_.Ge("googleapis.config/sessionIndex",g.authuser),e(g))})});b&&d.then(b,b);return d};UA=_.Kh.yG;VA=null;
_.YA=function(a,b){if("force"!==a.approvalprompt){a=_.WA(a);a.prompt="none";delete a.redirect_uri;delete a.approval_prompt;delete a.immediate;if(b=!b)VA?(a.client_id!==VA.client_id&&window.console&&window.console.log&&window.console.log("Ignoring mismatched page-level auth param client_id="+a.client_id),b=!0):(VA=a,b=!1);b||XA(a)}};
_.WA=function(a){var b=a.redirecturi||"postmessage",c=(0,_.qb)((a.scope||"").replace(/[\s\xa0]+/g," "));b={client_id:a.clientid,redirect_uri:b,response_type:"code token id_token gsession",scope:c};a.approvalprompt&&(b.approval_prompt=a.approvalprompt);a.state&&(b.state=a.state);a.openidrealm&&(b["openid.realm"]=a.openidrealm);c="offline"==a.accesstype?!0:(c=a.redirecturi)&&"postmessage"!=c;c&&(b.access_type="offline");a.requestvisibleactions&&(b.request_visible_actions=(0,_.qb)(a.requestvisibleactions.replace(/[\s\xa0]+/g,
" ")));a.after_redirect&&(b.after_redirect=a.after_redirect);a.cookiepolicy&&"none"!==a.cookiepolicy&&(b.cookie_policy=a.cookiepolicy);"undefined"!=typeof a.includegrantedscopes&&(b.include_granted_scopes=a.includegrantedscopes);a.e&&(b.e=a.e);(a=a.authuser||_.R("googleapis.config/sessionIndex"))&&(b.authuser=a);(a=_.R("useoriginassocialhost"))&&(b.use_origin_as_socialhost=a);return b};XA=function(a){_.fo("waaf0","signin","0");_.TA(a,function(b){_.fo("waaf1","signin","0");LA(b)})};
_.ZA=function(a){a=_.WA(a);_.Ge("oauth-flow/authWindowWidth",445);_.Ge("oauth-flow/authWindowHeight",615);XA(a)};_.$A=function(a){_.Pz.unsubscribe(_.Qz,a);_.Pz.subscribe(_.Qz,a)};
var gB,jB;_.bB=function(a){return a.cookiepolicy?!0:(_.aB("cookiepolicy is a required field.  See https://developers.google.com/+/web/signin/#button_attr_cookiepolicy for more information."),!1)};_.aB=function(a){window.console&&(window.console.error?window.console.error(a):window.console.log&&window.console.log(a))};_.fB=function(a,b){var c=_.on();_.oe(a,c);c=FA(c);if(_.bB(c)){var d=_.cB();_.dB(c);b?_.xe(b,"click",function(){_.eB(c,d)}):_.eB(c,d)}};
_.cB=function(){var a=new gB;_.$A(function(b){a.PA&&b&&(b.access_token&&_.Ge("isPlusUser",!0),b["g-oauth-window"]&&(a.PA=!1,_.Ef("OTA app install is no longer supported.")))});return a};gB=function(){this.PA=!1};_.dB=function(a){a=_.hB(a);_.iB(a.callback);_.KA(function(){_.YA(a)})};_.hB=function(a){jB(a);a.redirecturi&&delete a.redirecturi;Vz(function(b){return a[b]})||(a.authuser=0);return a};jB=function(a){/^\s*$/.test(a.scope||"")&&(a.scope="https://www.googleapis.com/auth/plus.login")};
_.iB=function(a){if("string"===typeof a)if(window[a])a=window[a];else{_.aB('Callback function named "'+a+'" not found');return}a&&_.$A(a)};_.eB=function(a,b){b.PA=!0;a=_.hB(a);_.ZA(a)};
_.K("gapi.auth.authorize",_.TA);_.K("gapi.auth.checkSessionState",function(a,b){var c=_.me();c.client_id=a.client_id;c.session_state=a.session_state;_.KA(function(){wA()?rA.send("check_session_state",c,function(d){b.call(null,d[0])},_.Cm):_.Jf.call(_.Mz,"check_session_state",sA(function(d){b.call(null,d)}),c.session_state,c.client_id)})});_.K("gapi.auth.getAuthHeaderValueForFirstParty",UA);_.K("gapi.auth.getToken",dA);
_.K("gapi.auth.getVersionInfo",function(a,b){_.KA(function(){var c=_.Ih()||"",d=null,e=null;c&&(e=c.split(" "),2==e.length&&(d=e[1]));d?wA()?rA.send("get_versioninfo",{xapisidHash:d,sessionIndex:b},function(f){a(f[0])},_.Cm):_.Jf.call(_.Mz,"get_versioninfo",sA(function(f){a(f)}),d,b):a()})});_.K("gapi.auth.init",_.KA);_.K("gapi.auth.setToken",_.eA);_.K("gapi.auth.signIn",function(a){_.fB(a)});_.K("gapi.auth.signOut",function(){var a=dA();a&&MA(a,a.cookie_policy)});
_.K("gapi.auth.unsafeUnpackIdToken",HA);_.K("gapi.auth._pimf",_.YA);_.K("gapi.auth._oart",EA);_.K("gapi.auth._guss",function(a){return gA(a).read()});

_.kB=function(a){return!!(a.clientid&&a.scope&&a.callback)};_.lB=function(){var a=_.on();_.kB(a)&&!_.R("disableRealtimeCallback")?_.dB(a):_.KA()};_.uk(function(){_.lB()});

_.lB=function(){var a=_.on();_.kB(a)&&!_.R("disableRealtimeCallback")&&_.dB(a)};

});
// Google Inc.
