document.writeln("<script async src=\"//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js\"></script>");
document.writeln("<!-- responsive -->");
document.writeln("<ins class=\"adsbygoogle\"");
document.writeln("     style=\"display:block\"");
document.writeln("     data-ad-client=\"ca-pub-7096258950800110\"");
document.writeln("     data-ad-slot=\"7496524382\"");
document.writeln("     data-ad-format=\"auto\"></ins>");
document.writeln("<script>");
document.writeln("(adsbygoogle = window.adsbygoogle || []).push({});");
document.writeln("</script>");